export const siteConfig = {
  name: "InfoBac",
  fullName: "InfoBac.md",
  tagline: "10 din oficiu la BAC informatică",
  description:
    "Platformă online de pregătire pentru certificările Certiport. Acceptat oficial de MEC pentru echivalarea probei de informatică la BAC. Făcut de elevi pentru elevi în Chișinău.",
  url:
    process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") ??
    "https://infobac.md",
  locale: "ro-MD",
  /**
   * Dynamic OG image generated by `app/opengraph-image.tsx` (Next file
   * convention). The literal `/og.png` static asset doesn't exist; this path
   * matches the file convention's emitted URL.
   */
  ogImage: "/opengraph-image",
  contact: {
    email: "hello@infobac.md",
    address: "Chișinău, Moldova",
  },
  geo: {
    latitude: 47.0105,
    longitude: 28.8638,
    addressLocality: "Chișinău",
    addressCountry: "MD",
    postalCode: "MD-2001",
  },
  foundingDate: "2025-09-01",
  social: {
    instagram: "https://instagram.com/infobac.md",
    tiktok: "https://tiktok.com/@infobac.md",
    youtube: "https://youtube.com/@infobac",
    telegram: "https://t.me/infobac",
  },
  keywords: [
    "bac informatică moldova",
    "bac informatică 2026",
    "10 din oficiu bac",
    "echivalare bac informatică",
    "echivalare certiport bac",
    "certiport moldova",
    "certiport chișinău",
    "examen certiport moldova",
    "it specialist certiport",
    "pathway certiport",
    "python bac moldova",
    "sql bac moldova",
    "networking bac moldova",
    "devices bac moldova",
    "certificare python moldova",
    "pregătire bac informatică online",
    "pregătire bac informatică chișinău",
    "curs informatică online moldova",
    "platformă bac moldova",
    "infobac",
    "infobac.md",
    "blog bac informatică",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
