// AUTO-GENERATED from scripts/questions.normalized.json — do not edit by hand.
// Re-run `node scripts/generate-question-modules.mjs` after extracting fresh content.

import type { Question } from "../types";

export const questions: readonly Question[] = [
  {
    id: `devices-001`,
    type: "single",
    topic: `General`,
    prompt: `Care serviciu Microsoft poate fi descris drept o suită de aplicații de productivitate găzduite în cloud?`,
    options: [`OneNote`, `Microsoft 365`, `SharePoint`, `Windows 365`],
    correctIndex: 1,
    explanation: `Microsoft 365 reunește instrumente precum Word, Excel și PowerPoint într-un mediu cloud accesibil de oriunde.`,
  },
  {
    id: `devices-002`,
    type: "single",
    topic: `General`,
    prompt: `Ce serviciu funcționează asemenea unui dosar cu separatoare, organizat pe secțiuni și pagini distincte?`,
    options: [`Microsoft 365`, `SharePoint`, `OneNote`, `Windows 365`],
    correctIndex: 2,
    explanation: `OneNote imită structura unui caiet clasic, împărțit în secțiuni cu pagini, ideal pentru notițe organizate.`,
  },
  {
    id: `devices-003`,
    type: "single",
    topic: `General`,
    prompt: `Ce platformă este folosită pentru a păstra documente partajate și a colabora la nivelul întregii organizații?`,
    options: [`OneNote`, `Windows 365`, `Microsoft 365`, `SharePoint`],
    correctIndex: 3,
    explanation: `SharePoint este conceput pentru depozitarea centralizată a documentelor și colaborarea între echipe.`,
  },
  {
    id: `devices-004`,
    type: "single",
    topic: `General`,
    prompt: `Care soluție permite rularea unui sistem de operare complet și poate fi accesată de pe Windows, MacOS sau ChromeOS?`,
    options: [`Windows 365`, `SharePoint`, `Microsoft 365`, `OneNote`],
    correctIndex: 0,
    explanation: `Windows 365 oferă un PC virtualizat în cloud (Cloud PC) la care te poți conecta de pe orice platformă.`,
  },
  {
    id: `devices-005`,
    type: "single",
    topic: `General`,
    prompt: `În ce secțiune din Settings ai putea modifica rezoluția monitorului și frecvența de reîmprospătare?`,
    options: [`Advanced display`, `Accessibility`, `Gaming`, `Device Manager`],
    correctIndex: 0,
    explanation: `Drumul către aceste setări este Settings > System > Display > Advanced display, unde sunt expuse rezoluția și refresh rate-ul.`,
  },
  {
    id: `devices-006`,
    type: "single",
    topic: `General`,
    prompt: `Microsoft Word se închide neașteptat. Care log din Event Viewer ar trebui consultat pentru detalii despre eroare?`,
    options: [`Security`, `System`, `Application`, `Setup`],
    correctIndex: 2,
    explanation: `Word fiind un program, evenimentele legate de el sunt înregistrate în log-ul Application.`,
  },
  {
    id: `devices-007`,
    type: "single",
    topic: `General`,
    prompt: `Niște fișiere criptate, având permisiuni configurate pe un volum NTFS, sunt mutate pe un stick FAT32. Care va fi rezultatul?`,
    options: [`Files still have permissions, encryption lost`, `Files lost their permissions and encryption`, `Files retained both encryption and permissions`, `Files are still encrypted, but permissions were lost`],
    correctIndex: 1,
    explanation: `Sistemul de fișiere FAT32 nu cunoaște nici criptarea EFS, nici lista de permisiuni NTFS, prin urmare ambele atribute dispar.`,
  },
  {
    id: `devices-008`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Third-party application installers cannot make changes to the Windows Registry'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Afirmația este Falsă — practic orice program de instalare scrie chei și valori în Registry.`,
  },
  {
    id: `devices-009`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Deleting the shortcut for a third-party application will automatically uninstall the application'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — un shortcut este doar o referință către executabil, iar ștergerea lui nu îndepărtează programul de pe sistem.`,
  },
  {
    id: `devices-010`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'By default, third-party apps are installed to different directories based on their architecture'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — aplicațiile pe 32 de biți merg în Program Files (x86), iar cele pe 64 de biți în Program Files.`,
  },
  {
    id: `devices-011`,
    type: "single",
    topic: `General`,
    prompt: `Pe Windows 10 Home, ce tip de cont creezi astfel încât să te poți autentifica pe mai multe dispozitive Windows și să beneficiezi de serviciile Microsoft?`,
    options: [`Microsoft Account`, `Domain Account`, `Local Administrator Account`, `Local Standard Account`],
    correctIndex: 0,
    explanation: `Doar contul Microsoft permite sincronizarea setărilor și a datelor între diferite dispozitive Windows.`,
  },
  {
    id: `devices-012`,
    type: "single",
    topic: `General`,
    prompt: `Ce categorie de informații este păstrată în mod predominant în Windows Registry?`,
    options: [`Profiles and application settings`, `Audio and video files`, `Microsoft 365 documents`, `HTTP cookies`],
    correctIndex: 0,
    explanation: `Registry funcționează ca o bază de date ierarhică unde se stochează configurațiile pentru profiluri și aplicații.`,
  },
  {
    id: `devices-013`,
    type: "single",
    topic: `General`,
    prompt: `Care funcționalitate Windows arată un dialog de confirmare în momentul în care utilizatorul vrea să instaleze un software?`,
    options: [`Active Directory (AD)`, `Windows Hello`, `User Account Control (UAC)`, `Windows Defender`],
    correctIndex: 2,
    explanation: `Mecanismul UAC ridică prompt-ul prin care întreabă dacă aplicația are permisiunea să facă modificări asupra sistemului.`,
  },
  {
    id: `devices-014`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Graphics cards render the images in a computer and display them on the monitor'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — exact aceasta este sarcina principală a unei plăci video: să producă imaginea și să o trimită spre monitor.`,
  },
  {
    id: `devices-015`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'VGA, DVI, HDMI, and DisplayPort are all graphics card outputs'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — fiecare dintre aceste interfețe reprezintă un tip de port video disponibil pe plăcile grafice.`,
  },
  {
    id: `devices-016`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Integrated graphics cards have their own built-in memory'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — soluțiile grafice integrate împrumută din memoria RAM a sistemului, neavând VRAM dedicat.`,
  },
  {
    id: `devices-017`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Graphics cards can access peripherals to help the CPU with processing speed'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — placa grafică este specializată pe procesarea imaginii și nu interacționează cu perifericele sistemului.`,
  },
  {
    id: `devices-018`,
    type: "single",
    topic: `General`,
    prompt: `După instalarea unei imprimante wireless, categoria Printers nu mai apare în Device Manager pentru imprimanta USB. Ce se întâmplă?`,
    options: [`A printer conflict exists`, `Windows 10 does not support multiple printers`, `The USB port is broken`, `The printer driver is missing`],
    correctIndex: 0,
    explanation: `Adăugarea imprimantei wireless a generat un conflict cu driverul imprimantei conectate prin USB.`,
  },
  {
    id: `devices-019`,
    type: "single",
    topic: `General`,
    prompt: `Conflict de imprimantă în Device Manager — care este următorul pas pentru a continua diagnosticul?`,
    options: [`Click Add legacy hardware on the Action menu`, `Click Show hidden devices on the View menu`, `Reinstall Windows`, `Run Windows Update`],
    correctIndex: 1,
    explanation: `Activând opțiunea View > Show hidden devices apar dispozitivele ascunse, inclusiv cele aflate în conflict.`,
  },
  {
    id: `devices-020`,
    type: "single",
    topic: `General`,
    prompt: `Personalizare desktop — poate fi modificat local elementul 'Logo on the Start button'?`,
    options: [`Yes`, `No`],
    correctIndex: 1,
    explanation: `Nu — sigla Windows de pe butonul Start nu este configurabilă de către utilizator.`,
  },
  {
    id: `devices-021`,
    type: "single",
    topic: `General`,
    prompt: `Personalizare desktop — poate fi setată local opțiunea 'Taskbar location'?`,
    options: [`Yes`, `No`],
    correctIndex: 0,
    explanation: `Da — bara de activități poate fi repoziționată pe oricare dintre cele patru margini ale ecranului.`,
  },
  {
    id: `devices-022`,
    type: "single",
    topic: `General`,
    prompt: `Personalizare desktop — pot fi ajustate local 'Display resolution and orientation'?`,
    options: [`Yes`, `No`],
    correctIndex: 0,
    explanation: `Da — atât rezoluția cât și orientarea ecranului se modifică din Settings > Display.`,
  },
  {
    id: `devices-023`,
    type: "single",
    topic: `General`,
    prompt: `Personalizare desktop — pot fi configurate local 'Folders that appear in the Start menu'?`,
    options: [`Yes`, `No`],
    correctIndex: 0,
    explanation: `Da — folderele afișate în meniul Start se aleg din Settings > Personalization > Start.`,
  },
  {
    id: `devices-024`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Driver updates can include non-Microsoft and manufacturer-installed drivers'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — prin Windows Update sosesc inclusiv drivere de la producători precum NVIDIA sau Intel.`,
  },
  {
    id: `devices-025`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Feature updates sometimes address security vulnerabilities'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — pe lângă funcționalități noi, feature update-urile aduc și corecturi de securitate.`,
  },
  {
    id: `devices-026`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Service packs are a collection of updates, patches, and hot fixes'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — un Service Pack este o colecție unitară ce reunește actualizările și fix-urile lansate anterior.`,
  },
  {
    id: `devices-027`,
    type: "single",
    topic: `General`,
    prompt: `Care permisiune NTFS îți oferă posibilitatea de a adăuga un subfolder?`,
    options: [`Read`, `Read & Execute`, `Write`, `Full Control`],
    correctIndex: 2,
    explanation: `Permisiunea Write conferă dreptul de a crea fișiere și foldere noi în interiorul resursei.`,
  },
  {
    id: `devices-028`,
    type: "single",
    topic: `General`,
    prompt: `Care permisiune NTFS îți permite să elimini un subfolder existent?`,
    options: [`Read`, `Write`, `Read & Execute`, `Full Control`],
    correctIndex: 3,
    explanation: `Doar Full Control include explicit dreptul de a șterge subfoldere și conținutul lor.`,
  },
  {
    id: `devices-029`,
    type: "single",
    topic: `General`,
    prompt: `Care permisiune NTFS îți permite să lansezi în execuție o aplicație?`,
    options: [`Write`, `Read & Execute`, `Full Control`, `Read`],
    correctIndex: 1,
    explanation: `Read & Execute combină dreptul de citire cu cel de a porni un fișier executabil.`,
  },
  {
    id: `devices-030`,
    type: "single",
    topic: `General`,
    prompt: `Identifică tipul de malware: 'Replicates itself, can be spread by email attachments'`,
    options: [`Logic Bomb`, `Ransomware`, `Trojan Horse`, `Worm`],
    correctIndex: 3,
    explanation: `Worm-ul (vierme) se autoreplică și se propagă tipic prin atașamente de email sau rețea.`,
  },
  {
    id: `devices-031`,
    type: "single",
    topic: `General`,
    prompt: `Identifică tipul de malware: 'Causes data inaccessibility until demands are met'`,
    options: [`Worm`, `Ransomware`, `Logic Bomb`, `Trojan Horse`],
    correctIndex: 1,
    explanation: `Ransomware-ul blochează accesul la date prin criptare și cere o sumă pentru deblocare.`,
  },
  {
    id: `devices-032`,
    type: "single",
    topic: `General`,
    prompt: `Identifică tipul de malware: 'Malicious software that appears to be a legitimate program'`,
    options: [`Worm`, `Logic Bomb`, `Trojan Horse`, `Ransomware`],
    correctIndex: 2,
    explanation: `Trojan Horse-ul se deghizează într-o aplicație autentică, dar conține cod răuvoitor.`,
  },
  {
    id: `devices-033`,
    type: "single",
    topic: `General`,
    prompt: `Identifică tipul de malware: 'Piece of code triggered by a condition, can cause damage'`,
    options: [`Logic Bomb`, `Worm`, `Ransomware`, `Trojan Horse`],
    correctIndex: 0,
    explanation: `Logic Bomb-ul rămâne dormant până la întrunirea unei anumite condiții (dată, eveniment), când se activează.`,
  },
  {
    id: `devices-034`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Domain administrators have complete access to files, directories, and services on the local server'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — un Domain Admin deține control deplin asupra serverelor membre ale domeniului respectiv.`,
  },
  {
    id: `devices-035`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Domain administrators can create domain users and assign rights to those users'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — administrarea conturilor și acordarea de drepturi reprezintă atribuții de bază ale Domain Admin-ului.`,
  },
  {
    id: `devices-036`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Domain administrators are prevented from lockouts'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — și un Domain Admin poate fi blocat la introducerea greșită a parolei. Doar contul built-in Administrator are acest privilegiu.`,
  },
  {
    id: `devices-037`,
    type: "single",
    topic: `General`,
    prompt: `În Task Manager, ce filă folosești pentru a închide o aplicație care nu mai răspunde?`,
    options: [`App history`, `Performance`, `Startup apps`, `Processes`],
    correctIndex: 3,
    explanation: `Din fila Processes selectezi aplicația și alegi End Task pentru a o forța să se închidă.`,
  },
  {
    id: `devices-038`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Restarting your computer will wipe the RAM storage'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — memoria RAM este volatilă, iar la restart conținutul ei este șters complet.`,
  },
  {
    id: `devices-039`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Opening a program loads the application into RAM'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — la lansare, executabilul este transferat de pe stocare în memoria RAM pentru a putea rula.`,
  },
  {
    id: `devices-040`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Reading data from RAM is slower than reading data from the hard disk drive'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — RAM-ul este cu mai multe ordine de mărime mai rapid decât un HDD.`,
  },
  {
    id: `devices-041`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Aplicațiile pe 64 de biți sunt instalate implicit în C:\\Program Files (x86)'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — folderul (x86) găzduiește aplicațiile pe 32 de biți; cele pe 64 de biți merg în Program Files fără sufix.`,
  },
  {
    id: `devices-042`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Deleting an application folder uninstalls it and removes registry settings'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — ștergerea manuală a folderului lasă în urmă chei de Registry. Pentru o curățare corectă se folosește dezinstalatorul.`,
  },
  {
    id: `devices-043`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'A UAC prompt displays when Standard Users install apps in Program Files'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — folderul Program Files este protejat, iar instalarea acolo necesită aprobare prin UAC.`,
  },
  {
    id: `devices-044`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'A Microsoft account is necessary to configure facial recognition'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — Windows Hello poate fi activat și pe un cont local, fără a fi nevoie de cont Microsoft.`,
  },
  {
    id: `devices-045`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'A compatible infrared (IR) camera is needed to set up facial recognition'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — recunoașterea facială prin Windows Hello are nevoie de o cameră infraroșu compatibilă.`,
  },
  {
    id: `devices-046`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'If facial recognition fails, the user will be automatically logged in with the saved password'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — dacă autentificarea facială eșuează, utilizatorul trebuie să introducă manual PIN-ul sau parola.`,
  },
  {
    id: `devices-047`,
    type: "single",
    topic: `General`,
    prompt: `File server FS1, share 'Training' — poți deschide un subfolder accesat prin \\\\FS1\\Training?`,
    options: [`Yes`, `No`],
    correctIndex: 0,
    explanation: `Da — drepturile de Read prin share permit deschiderea subfolderelor partajate.`,
  },
  {
    id: `devices-048`,
    type: "single",
    topic: `General`,
    prompt: `File server FS1, share 'Training' — poți crea un subfolder nou prin \\\\FS1\\Training?`,
    options: [`Yes`, `No`],
    correctIndex: 1,
    explanation: `Nu — share permissions nu îți acordă dreptul de Write necesar pentru a crea subfoldere.`,
  },
  {
    id: `devices-049`,
    type: "single",
    topic: `General`,
    prompt: `File server FS1 — dacă te conectezi prin Remote Desktop la FS1, poți crea un subfolder în D:\\Projects\\Training?`,
    options: [`Yes`, `No`],
    correctIndex: 1,
    explanation: `Nu — permisiunile NTFS aplicate folderului blochează scrierea, indiferent de modul în care te-ai conectat.`,
  },
  {
    id: `devices-050`,
    type: "single",
    topic: `General`,
    prompt: `Active Directory: 'It allows users to use their credentials throughout the network'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — AD furnizează un mecanism de Single Sign-On valabil pe toată rețeaua organizației.`,
  },
  {
    id: `devices-051`,
    type: "single",
    topic: `General`,
    prompt: `Active Directory: 'It allows efficient searching of files on your computer'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — AD se ocupă de identitate și obiecte de rețea, nu de indexarea fișierelor locale (asta face Windows Search).`,
  },
  {
    id: `devices-052`,
    type: "single",
    topic: `General`,
    prompt: `Active Directory: 'It allows all users to configure their own rights'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — drepturile sunt atribuite și configurate exclusiv de către administratori.`,
  },
  {
    id: `devices-053`,
    type: "single",
    topic: `General`,
    prompt: `Calculatorul nu preia noile politici de Group Policy de securitate. Trebuie să forțezi reaplicarea lor. Cum procedezi?`,
    options: [`Run gpupdate /force from command prompt`, `Open Local Security Policy and choose Reload`, `Run gpresult /h from command prompt`, `Open System Information and Refresh`],
    correctIndex: 0,
    explanation: `Comanda gpupdate /force forțează reaplicarea integrală a politicilor; gpresult doar generează un raport asupra celor existente.`,
  },
  {
    id: `devices-054`,
    type: "single",
    topic: `General`,
    prompt: `Windows Defender a izolat în carantină un fișier despre care echipa IT a confirmat că este un fals pozitiv. Care este pasul corect?`,
    options: [`Find and delete the file in Windows Explorer`, `Reinstall the program`, `Run the scan again`, `Recover the file from quarantine`],
    correctIndex: 3,
    explanation: `Întrucât fișierul este sigur, trebuie restaurat din carantină pentru a redeveni utilizabil.`,
  },
  {
    id: `devices-055`,
    type: "single",
    topic: `General`,
    prompt: `Folosești o imprimantă veche printr-un adaptor USB-to-serial. Vrei să modifici baud rate, data bits și parity. Ce categorie din Device Manager folosești?`,
    options: [`Printers`, `Print queues`, `Ports (COM & LPT)`, `Storage controllers`],
    correctIndex: 2,
    explanation: `Parametrii unei conexiuni seriale se ajustează din categoria Ports (COM & LPT), pe portul COM corespunzător.`,
  },
  {
    id: `devices-056`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'A computer's max supported RAM capacity and speed are determined by the motherboard'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — capacitatea maximă și frecvența RAM-ului sunt impuse de specificațiile plăcii de bază.`,
  },
  {
    id: `devices-057`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'You can upgrade an Intel processor to AMD without changing the motherboard'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — procesoarele Intel și AMD folosesc socket-uri incompatibile, deci o astfel de migrare implică și schimbarea plăcii de bază.`,
  },
  {
    id: `devices-058`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'BIOS settings are stored on the motherboard'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — BIOS-ul rezidă pe un cip al plăcii de bază, iar setările sunt menținute prin bateria CMOS.`,
  },
  {
    id: `devices-059`,
    type: "single",
    topic: `General`,
    prompt: `Un utilizator dorește să proiecteze ecranul wireless pe un televizor smart. În ce zonă din System settings găsește această opțiune?`,
    options: [`Nearby sharing`, `Display`, `Projecting to this PC`, `Remote Desktop`],
    correctIndex: 1,
    explanation: `Conectarea unui display wireless (Miracast) se realizează din Settings > System > Display.`,
  },
  {
    id: `devices-060`,
    type: "single",
    topic: `General`,
    prompt: `Numele rețelei (SSID) apare în lista de Wi-Fi, dar niciun angajat nu reușește să se conecteze. Ce faci?`,
    options: [`Execute ipconfig /renew`, `Check each employee's Ethernet cable`, `Reboot the access point or router`, `Verify that Wi-Fi is enabled`],
    correctIndex: 2,
    explanation: `Atunci când rețeaua este vizibilă, dar nimeni nu se poate autentifica, soluția uzuală este restartul access point-ului sau routerului.`,
  },
  {
    id: `devices-061`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Setting up a new drive is done through Disk Management'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — Disk Management este utilitarul prin care un drive nou este inițializat, partiționat și formatat.`,
  },
  {
    id: `devices-062`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Freeing up disk space for a slow computer is done through Disk Management'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — eliberarea spațiului de pe disc se realizează cu Disk Cleanup, nu cu Disk Management.`,
  },
  {
    id: `devices-063`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Manually updating drivers can be done through the Device Manager'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — în Device Manager dai click dreapta pe dispozitiv și alegi Update driver.`,
  },
  {
    id: `devices-064`,
    type: "single",
    topic: `General`,
    prompt: `Ai un stick USB de 4GB pe care îl folosești pe camere foto vechi, console și calculatoare non-Windows. Ce sistem de fișiere alegi pentru maximă compatibilitate?`,
    options: [`ExFAT`, `FAT16`, `NTFS`, `FAT32`],
    correctIndex: 3,
    explanation: `FAT32 este cel mai larg suportat sistem de fișiere și funcționează aproape pe orice dispozitiv existent.`,
  },
  {
    id: `devices-065`,
    type: "single",
    topic: `General`,
    prompt: `După un upgrade la Windows 10, observi că spațiul ocupat pe disc a crescut considerabil. Vrei să eliberezi cât mai mult spațiu. Ce faci?`,
    options: [`Defragment the hard drive`, `Remove and reinstall all applications`, `Run Disk Cleanup to remove previous Windows installation(s)`, `Adjust system settings to allocate more space`],
    correctIndex: 2,
    explanation: `Disk Cleanup poate elimina folderul Windows.old (instalarea anterioară), recuperând frecvent zeci de gigabytes.`,
  },
  {
    id: `devices-066`,
    type: "single",
    topic: `General`,
    prompt: `Windows Backup: 'Can be used to back up files and folders to the cloud'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — Windows Backup salvează fișierele și folderele direct în OneDrive (cloud).`,
  },
  {
    id: `devices-067`,
    type: "single",
    topic: `General`,
    prompt: `Windows Backup: 'Can be used to back up saved passwords and credentials'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — printre elementele incluse în backup se numără și parolele cu credențialele salvate.`,
  },
  {
    id: `devices-068`,
    type: "single",
    topic: `General`,
    prompt: `Windows Backup: 'Can be used to back up files and folders to physical media'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — versiunea modernă Windows Backup vizează cloud-ul. Pentru media fizică (HDD extern) se folosește Backup and Restore.`,
  },
  {
    id: `devices-069`,
    type: "single",
    topic: `General`,
    prompt: `În Windows 10, în care zonă din Settings se ajustează parametrii Narrator-ului?`,
    options: [`Apps`, `Accessibility`, `Ease of Access`, `Personalization`],
    correctIndex: 2,
    explanation: `Narrator-ul este o funcție de accesibilitate, accesibilă din Settings > Ease of Access.`,
  },
  {
    id: `devices-070`,
    type: "single",
    topic: `General`,
    prompt: `Un coleg nu reușește să acceseze rețeaua și ai nevoie să afli rapid IP-ul atribuit și default gateway-ul. Ce comandă rulezi?`,
    options: [`ipconfig`, `ping 0.0.0.0`, `ipconfig /release`, `ping 127.0.0.1`],
    correctIndex: 0,
    explanation: `Comanda ipconfig listează configurația rețelei, inclusiv adresa IP, masca de subrețea și gateway-ul implicit.`,
  },
  {
    id: `devices-071`,
    type: "single",
    topic: `General`,
    prompt: `Vrei copii de siguranță automate ale folderului D:\\Books la fiecare 10 minute, fără a depinde de internet, și posibilitatea de a restaura versiuni anterioare. Ce configurezi?`,
    options: [`Configure System Restore`, `Configure OneDrive to sync`, `Use Backup and Restore to create a system image`, `Enable File History to save copies to a network drive`],
    correctIndex: 3,
    explanation: `File History execută backup-uri periodice către un drive extern sau de rețea și păstrează versiuni anterioare ale fișierelor.`,
  },
  {
    id: `devices-072`,
    type: "single",
    topic: `General`,
    prompt: `Pregătești instalarea Windows 10 pe un PC nou care are un singur hard disk. Cum creezi mediul de instalare?`,
    options: [`Run Media Creation tool on internal hard drive`, `Copy Windows 10 ISO to a USB drive`, `Copy Windows 10 ISO to internal hard drive`, `Run Media Creation tool on a USB drive`],
    correctIndex: 3,
    explanation: `Media Creation Tool generează un USB bootabil; instalarea nu poate porni de pe discul intern care urmează a fi formatat.`,
  },
  {
    id: `devices-073`,
    type: "single",
    topic: `General`,
    prompt: `În Windows 10 Home, ce tip de cont îți este necesar pentru a putea modifica fișierele de sistem?`,
    options: [`Administrator User Account`, `Standard User Account`, `Domain User Account`, `Microsoft Account`],
    correctIndex: 0,
    explanation: `Fișierele de sistem sunt protejate, iar modificarea lor cere drepturi de administrator local.`,
  },
  {
    id: `devices-074`,
    type: "single",
    topic: `General`,
    prompt: `Nu reușești să instalezi o aplicație din Microsoft Store. Ce instrument folosești pentru depanare?`,
    options: [`Device Manager`, `Installed Apps`, `WSReset.exe`, `Task Manager`],
    correctIndex: 2,
    explanation: `Utilitarul WSReset.exe șterge cache-ul Microsoft Store și rezolvă majoritatea problemelor de instalare.`,
  },
  {
    id: `devices-075`,
    type: "single",
    topic: `General`,
    prompt: `Trebuie să formatezi un SSD de 3TB pe care vei rula Windows 10 și vrei să reduci riscul de pierdere a datelor. Ce sistem de fișiere alegi?`,
    options: [`NTFS`, `FAT32`, `exFAT`, `FAT16`],
    correctIndex: 0,
    explanation: `NTFS este robust, oferă jurnalizare, suportă permisiuni și criptare la nivel de fișier.`,
  },
  {
    id: `devices-076`,
    type: "single",
    topic: `General`,
    prompt: `Trebuie să formatezi un SSD de 3TB pe care vei rula Windows 10 și vrei să reduci riscul de pierdere a datelor. Ce stil de partiționare alegi?`,
    options: [`MBR`, `GPT`],
    correctIndex: 1,
    explanation: `GPT este obligatoriu pentru drive-uri de peste 2TB și păstrează o copie de rezervă a tabelei de partiții.`,
  },
  {
    id: `devices-077`,
    type: "single",
    topic: `General`,
    prompt: `Windows Registry: 'Settings are persistent across system restarts'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — Registry-ul este stocat pe disc, deci configurațiile se păstrează după restart.`,
  },
  {
    id: `devices-078`,
    type: "single",
    topic: `General`,
    prompt: `Windows Registry: 'Application installers can modify the registry'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — programele de instalare scriu și citesc chei din Registry pentru a-și salva configurația.`,
  },
  {
    id: `devices-079`,
    type: "single",
    topic: `General`,
    prompt: `Windows Registry: 'Changes to settings are immediately backed up to OneDrive'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — Registry-ul rămâne local pe calculator, fără sincronizare automată cu OneDrive.`,
  },
  {
    id: `devices-080`,
    type: "single",
    topic: `General`,
    prompt: `Windows Update: 'Optional updates are accessible directly from Windows Update Advanced Options'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — secțiunea Optional updates apare în Windows Update > Advanced Options.`,
  },
  {
    id: `devices-081`,
    type: "single",
    topic: `General`,
    prompt: `Windows Update: 'Uninstall for recently installed updates can be accessed under update history'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — din Update History găsești opțiunea de a dezinstala update-urile recente.`,
  },
  {
    id: `devices-082`,
    type: "single",
    topic: `General`,
    prompt: `Windows Update: 'Required updates pending will only install when active hours are set'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — actualizările obligatorii se instalează inclusiv în afara intervalului definit ca active hours.`,
  },
  {
    id: `devices-083`,
    type: "single",
    topic: `General`,
    prompt: `Conector: 'Can deliver both power and data to a device'`,
    options: [`USB Type-C`, `VGA`, `DisplayPort`, `HDMI`],
    correctIndex: 0,
    explanation: `USB Type-C transportă atât alimentare, cât și date prin același cablu unificat.`,
  },
  {
    id: `devices-084`,
    type: "single",
    topic: `General`,
    prompt: `Conector: 'Typically found on legacy monitors and computers'`,
    options: [`HDMI`, `USB Type-C`, `VGA`, `DisplayPort`],
    correctIndex: 2,
    explanation: `VGA datează din 1987 și este standardul cel mai întâlnit pe echipamente vechi.`,
  },
  {
    id: `devices-085`,
    type: "single",
    topic: `General`,
    prompt: `Conector: 'Used by monitors and computers, but NOT game consoles'`,
    options: [`HDMI`, `VGA`, `DisplayPort`, `USB Type-C`],
    correctIndex: 2,
    explanation: `DisplayPort este uzual pe monitoare PC, în timp ce consolele preferă HDMI.`,
  },
  {
    id: `devices-086`,
    type: "single",
    topic: `General`,
    prompt: `Conector: 'Used by televisions, computers, game consoles, and projectors'`,
    options: [`VGA`, `DisplayPort`, `USB Type-C`, `HDMI`],
    correctIndex: 3,
    explanation: `HDMI este cea mai universală interfață audio-video și se găsește pe TV-uri, PC-uri, console și proiectoare.`,
  },
  {
    id: `devices-087`,
    type: "single",
    topic: `General`,
    prompt: `Care este rolul principal al Windows Registry?`,
    options: [`Verifies the integrity of files on the hard drive`, `Indexes data in the file system to improve searching`, `Stores data for profiles, applications, and hardware drivers`, `Provides protection from malicious software`],
    correctIndex: 2,
    explanation: `Registry-ul reprezintă baza de date centrală în care Windows păstrează configurările pentru profiluri, programe și drivere.`,
  },
  {
    id: `devices-088`,
    type: "single",
    topic: `General`,
    prompt: `Un smartphone conectat prin USB nu este detectat și ai nevoie să instalezi cel mai recent driver. Ce instrument folosești?`,
    options: [`Phone and Modem`, `System Configuration`, `Device Manager`, `Windows Mobility Center`],
    correctIndex: 2,
    explanation: `Device Manager este locul unde se gestionează și se actualizează driverele dispozitivelor conectate.`,
  },
  {
    id: `devices-089`,
    type: "single",
    topic: `General`,
    prompt: `Drivers: 'Windows not finding a new driver means there is not an updated driver available'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — producătorul componentei poate publica pe site-ul propriu un driver mai nou decât cel detectat de Windows.`,
  },
  {
    id: `devices-090`,
    type: "single",
    topic: `General`,
    prompt: `Drivers: 'Before reinstalling a driver, uninstall the driver then restart the PC'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — best practice-ul este uninstall, apoi restart, după care se face reinstalarea curată.`,
  },
  {
    id: `devices-091`,
    type: "single",
    topic: `General`,
    prompt: `Drivers: 'Windows will allow a driver to be rolled back to any previous version'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — Roll Back Driver permite revenirea doar la versiunea instalată anterior, nu la oricare versiune mai veche.`,
  },
  {
    id: `devices-092`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de semnal transportă DisplayPort?`,
    options: [`Audio`, `Video`, `Audio & Video`],
    correctIndex: 2,
    explanation: `DisplayPort poate transmite simultan flux audio și video printr-un singur cablu.`,
  },
  {
    id: `devices-093`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de semnal transportă VGA?`,
    options: [`Audio`, `Video`, `Audio & Video`],
    correctIndex: 1,
    explanation: `VGA este un standard analogic exclusiv video, fără canal de sunet.`,
  },
  {
    id: `devices-094`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de semnal transportă HDMI?`,
    options: [`Audio`, `Video`, `Audio & Video`],
    correctIndex: 2,
    explanation: `HDMI duce și sunet, și imagine pe același cablu, fiind o interfață audio-video integrată.`,
  },
  {
    id: `devices-095`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de semnal transportă S/PDIF Optical?`,
    options: [`Audio`, `Video`, `Audio & Video`],
    correctIndex: 0,
    explanation: `S/PDIF Optical transportă strict audio digital, prin fibră optică.`,
  },
  {
    id: `devices-096`,
    type: "single",
    topic: `General`,
    prompt: `Authenticator: 'Can send push notifications for both local and Microsoft accounts'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — push-urile Microsoft Authenticator funcționează doar cu conturi Microsoft sau Azure AD, nu cu conturi locale.`,
  },
  {
    id: `devices-097`,
    type: "single",
    topic: `General`,
    prompt: `Authenticator: 'You can use it to login if you forget your password'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — Authenticator reprezintă al doilea factor (2FA) și nu înlocuiește parola.`,
  },
  {
    id: `devices-098`,
    type: "single",
    topic: `General`,
    prompt: `Authenticator: 'Generates time-based one-time passwords as part of MFA'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — aplicația generează coduri TOTP care se reînnoiesc la fiecare 30 de secunde.`,
  },
  {
    id: `devices-099`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'RAM is non-volatile'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — RAM-ul este o memorie volatilă; conținutul se șterge atunci când dispare alimentarea.`,
  },
  {
    id: `devices-100`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'A low latency HDD is faster than an SSD'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — chiar și cele mai performante HDD-uri rămân în urma oricărui SSD modern în privința vitezei.`,
  },
  {
    id: `devices-101`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'Physical storage includes SSD, HDD, and flash drives'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — toate cele trei sunt mediumuri fizice de stocare a datelor.`,
  },
  {
    id: `devices-102`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'NTFS supports a maximum file size of 4GB'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — limita de 4GB pentru un fișier este specifică FAT32. NTFS suportă fișiere de ordinul terabyților.`,
  },
  {
    id: `devices-103`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'FAT32 supports partitions up to 32TB'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — partițiile FAT32 sunt limitate la aproximativ 2TB; valoarea de 32TB nu reflectă realitatea.`,
  },
  {
    id: `devices-104`,
    type: "single",
    topic: `General`,
    prompt: `Adevărat sau Fals: 'ExFAT is ideal for flash drives and supports storage media up to 256TB'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — ExFAT a fost proiectat pentru dispozitive flash și nu suferă de limita de 4GB pe fișier specifică FAT32.`,
  },
  {
    id: `devices-105`,
    type: "single",
    topic: `General`,
    prompt: `Cristina se conectează la Wi-Fi-ul unei cafenele din oraș. Ce profil de rețea ar trebui să selecteze în Windows?`,
    options: [`Private`, `Public`, `Domain`, `Guest`],
    correctIndex: 1,
    explanation: `Profilul Public se folosește în spații publice (cafenele, aeroporturi); calculatorul rămâne ascuns, partajarea e dezactivată, iar firewall-ul aplică reguli mai stricte.`,
  },
  {
    id: `devices-106`,
    type: "single",
    topic: `General`,
    prompt: `Pe o rețea de tip Private, computerul este descoperibil de către celelalte aparate din rețea. Adevărat sau Fals?`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — în profilul Private (acasă, birou de încredere) PC-ul este vizibil, iar partajarea fișierelor și imprimantelor este permisă.`,
  },
  {
    id: `devices-107`,
    type: "single",
    topic: `General`,
    prompt: `Care este consecința dezactivării Windows Defender Firewall?`,
    options: [`Windows Update nu mai funcționează`, `PC-ul devine vulnerabil la accesul neautorizat din rețea`, `Antivirusul Windows Defender se dezactivează automat`, `Nu mai poți accesa internetul`],
    correctIndex: 1,
    explanation: `Firewall-ul filtrează conexiunile primite din rețea; fără el, calculatorul rămâne expus tentativelor de acces neautorizat. Componenta antivirus este complet separată.`,
  },
  {
    id: `devices-108`,
    type: "single",
    topic: `General`,
    prompt: `Care este distincția fundamentală dintre profilul Private și cel Public într-o rețea Windows?`,
    options: [`Private necesită parolă, Public nu`, `Private permite file sharing și discovery, Public le blochează`, `Public e mai rapid decât Private`, `Private funcționează doar cu Ethernet`],
    correctIndex: 1,
    explanation: `În Private, partajarea și descoperirea dispozitivelor sunt activate; în Public, ambele sunt dezactivate. Diferența vizează securitatea, nu performanța.`,
  },
  {
    id: `devices-109`,
    type: "single",
    topic: `General`,
    prompt: `După ce rulezi ipconfig vezi adresa 169.254.15.200. Ce semnifică acest lucru?`,
    options: [`IP static configurat manual`, `Conexiune VPN activă`, `PC-ul nu a putut obține un IP de la serverul DHCP`, `Adresa IP a routerului`],
    correctIndex: 2,
    explanation: `Intervalul 169.254.x.x corespunde APIPA și apare atunci când DHCP nu răspunde, calculatorul auto-atribuindu-și o adresă; nu există conectivitate la internet.`,
  },
  {
    id: `devices-110`,
    type: "single",
    topic: `General`,
    prompt: `Ce interval de adrese IP este rezervat pentru APIPA?`,
    options: [`192.168.x.x`, `10.0.x.x`, `169.254.x.x`, `172.16.x.x`],
    correctIndex: 2,
    explanation: `APIPA folosește exclusiv blocul 169.254.0.1 - 169.254.255.254, distinct de intervalele standard pentru IP-uri private.`,
  },
  {
    id: `devices-111`,
    type: "single",
    topic: `General`,
    prompt: `Un PC primește o adresă APIPA (169.254.x.x). Care ar fi cel mai rezonabil prim pas în diagnostic?`,
    options: [`Reinstalează Windows`, `Verifică conexiunea la router/switch și dacă DHCP funcționează`, `Schimbă placa de rețea`, `Dezactivează firewall-ul`],
    correctIndex: 1,
    explanation: `Apariția unui APIPA arată că serverul DHCP nu a răspuns. Trebuie verificat cablul, routerul și starea serviciului DHCP.`,
  },
  {
    id: `devices-112`,
    type: "single",
    topic: `General`,
    prompt: `Cum poate fi descris Safe Mode din Windows?`,
    options: [`Un mod care criptează toate fișierele`, `Un mod de boot cu drivere și fișiere minime, pentru diagnostic`, `Un mod care blochează accesul la internet permanent`, `Un mod de backup automat`],
    correctIndex: 1,
    explanation: `Safe Mode pornește Windows-ul cu un set redus de drivere și componente, util pentru diagnostic — dacă sistemul funcționează aici, problema vine probabil de la un driver sau program terț.`,
  },
  {
    id: `devices-113`,
    type: "single",
    topic: `General`,
    prompt: `Ce variantă de Safe Mode oferă acces la internet?`,
    options: [`Safe Mode`, `Safe Mode with Networking`, `Safe Mode with Command Prompt`, `Niciuna`],
    correctIndex: 1,
    explanation: `Safe Mode with Networking încarcă în plus driverele de rețea, ceea ce permite descărcarea de drivere sau actualizări online.`,
  },
  {
    id: `devices-114`,
    type: "single",
    topic: `General`,
    prompt: `Cum se ajunge la Advanced Startup Options pentru a porni în Safe Mode?`,
    options: [`Apasă F1 la pornire`, `Din Settings > Update & Security > Recovery > Restart now, sau Shift + Restart`, `Din Control Panel > System`, `Din Task Manager > Startup`],
    correctIndex: 1,
    explanation: `Drumul standard este Settings > Update & Security > Recovery > Advanced startup > Restart now; alternativ, ții Shift apăsat și apeși Restart.`,
  },
  {
    id: `devices-115`,
    type: "single",
    topic: `General`,
    prompt: `Safe Mode with Command Prompt încarcă interfața grafică obișnuită. Adevărat sau Fals?`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — în acest regim utilizatorul vede doar o consolă de comandă, fără desktop-ul tradițional. Este destinat utilizatorilor avansați.`,
  },
  {
    id: `devices-116`,
    type: "single",
    topic: `General`,
    prompt: `Care serviciu Microsoft asigură stocarea cloud integrată direct în Windows 10?`,
    options: [`SharePoint`, `OneDrive`, `Azure`, `Teams`],
    correctIndex: 1,
    explanation: `OneDrive este componenta de stocare cloud personală integrată în Windows; SharePoint vizează colaborarea la nivel de organizație.`,
  },
  {
    id: `devices-117`,
    type: "single",
    topic: `General`,
    prompt: `Ce reprezintă funcția OneDrive Files On-Demand?`,
    options: [`Fișierele sunt șterse automat după 30 de zile`, `Poți vedea fișierele din cloud fără să le descarci pe PC`, `Fișierele sunt criptate automat`, `Fișierele sunt partajate automat cu toți contactele`],
    correctIndex: 1,
    explanation: `Files On-Demand afișează fișierele cloud în File Explorer fără a ocupa spațiu pe disc; descărcarea efectivă are loc abia la deschidere.`,
  },
  {
    id: `devices-118`,
    type: "single",
    topic: `General`,
    prompt: `Un fișier OneDrive marcat cu opțiunea 'Always available on this device' poate fi deschis și fără conexiune la internet. Adevărat sau Fals?`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — această setare descarcă o copie locală pe PC, astfel încât fișierul să fie accesibil chiar și offline.`,
  },
  {
    id: `devices-119`,
    type: "single",
    topic: `General`,
    prompt: `Ce categorie de malware adună informații despre utilizator în lipsa consimțământului acestuia?`,
    options: [`Ransomware`, `Adware`, `Spyware`, `Logic Bomb`],
    correctIndex: 2,
    explanation: `Spyware-ul (de la spy = spion) operează discret și colectează date precum istoricul navigării, parolele sau apăsările de taste.`,
  },
  {
    id: `devices-120`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de atac folosește mesaje de email contrafăcute, ce par trimise dintr-o sursă legitimă, pentru a sustrage date personale?`,
    options: [`Keylogger`, `Phishing`, `Adware`, `Worm`],
    correctIndex: 1,
    explanation: `Phishing-ul (literal 'pescuit') livrează emailuri imitate (bancă, servicii online) care solicită parole sau date bancare.`,
  },
  {
    id: `devices-121`,
    type: "single",
    topic: `General`,
    prompt: `Care este efectul unui keylogger?`,
    options: [`Blochează tastatura`, `Înregistrează fiecare tastă apăsată de utilizator`, `Criptează fișierele`, `Afișează reclame`],
    correctIndex: 1,
    explanation: `Termenul provine de la key (tastă) și logger (înregistrator); programul reține tot ce tastezi: parole, mesaje, date bancare etc.`,
  },
  {
    id: `devices-122`,
    type: "single",
    topic: `General`,
    prompt: `Ce desemnează social engineering în domeniul securității IT?`,
    options: [`Un tip de criptare`, `Manipulare psihologică pentru a obține informații confidențiale`, `Un protocol de rețea`, `Un software antivirus`],
    correctIndex: 1,
    explanation: `În social engineering atacatorul exploatează oamenii, nu sistemele; de exemplu, se prezintă drept coleg din IT și solicită parola.`,
  },
  {
    id: `devices-123`,
    type: "single",
    topic: `General`,
    prompt: `Ce categorie de malware bombardează utilizatorul cu reclame nedorite?`,
    options: [`Spyware`, `Trojan Horse`, `Adware`, `Ransomware`],
    correctIndex: 2,
    explanation: `Adware-ul (ad = reclamă, ware = software) afișează ferestre pop-up și bannere publicitare nesolicitate.`,
  },
  {
    id: `devices-124`,
    type: "single",
    topic: `General`,
    prompt: `Ce se întâmplă cu informațiile din RAM atunci când calculatorul intră în Sleep mode?`,
    options: [`Sunt șterse complet`, `Sunt salvate pe hard disk`, `RAM rămâne alimentată, datele sunt păstrate`, `Sunt transferate în cloud`],
    correctIndex: 2,
    explanation: `În Sleep, RAM-ul primește în continuare un flux mic de curent, iar datele rămân intacte, astfel încât revenirea este aproape instantanee. Dacă alimentarea cade, datele se pierd.`,
  },
  {
    id: `devices-125`,
    type: "single",
    topic: `General`,
    prompt: `Ce se întâmplă cu datele din RAM la intrarea în Hibernate?`,
    options: [`RAM rămâne alimentată`, `Conținutul RAM-ului este salvat pe disc (hiberfil.sys), apoi PC-ul se oprește complet`, `Datele sunt șterse`, `Datele sunt trimise în cloud`],
    correctIndex: 1,
    explanation: `Hibernate transferă conținutul RAM-ului într-un fișier pe disc (hiberfil.sys) și apoi închide complet calculatorul, consumul devenind zero. La pornire, totul este restaurat de pe disc.`,
  },
  {
    id: `devices-126`,
    type: "single",
    topic: `General`,
    prompt: `Care opțiune de power consumă cea mai puțină energie?`,
    options: [`Sleep`, `Hibernate`, `Lock screen`, `Balanced mode`],
    correctIndex: 1,
    explanation: `Hibernate aduce consumul la zero deoarece PC-ul este oprit. Sleep mai consumă puțin curent pentru a menține RAM-ul alimentat.`,
  },
  {
    id: `devices-127`,
    type: "single",
    topic: `General`,
    prompt: `Ce power plan recomandă Windows ca fiind potrivit pentru majoritatea utilizatorilor?`,
    options: [`Power saver`, `High performance`, `Balanced`, `Ultimate performance`],
    correctIndex: 2,
    explanation: `Planul Balanced reprezintă compromisul implicit între performanță și economie de energie.`,
  },
  {
    id: `devices-128`,
    type: "single",
    topic: `General`,
    prompt: `Ce este MDM (Mobile Device Management)?`,
    options: [`Un protocol de rețea wireless`, `Software care permite companiilor să gestioneze dispozitivele mobile ale angajaților de la distanță`, `Un tip de criptare pentru telefoane`, `O aplicație de backup`],
    correctIndex: 1,
    explanation: `Soluțiile MDM permit administrarea centralizată a telefoanelor și tabletelor: impunerea politicilor de parolă, distribuirea aplicațiilor și remote wipe.`,
  },
  {
    id: `devices-129`,
    type: "single",
    topic: `General`,
    prompt: `Ce semnificație are acronimul BYOD?`,
    options: [`Back Your Own Data`, `Bring Your Own Device`, `Build Your Own Desktop`, `Backup Your Online Documents`],
    correctIndex: 1,
    explanation: `BYOD înseamnă Bring Your Own Device — angajatul își aduce propriul dispozitiv la serviciu, iar compania poate impune politici de securitate peste el.`,
  },
  {
    id: `devices-130`,
    type: "single",
    topic: `General`,
    prompt: `Ce face funcția Remote Wipe?`,
    options: [`Ștergerea de la distanță a tuturor datelor de pe un dispozitiv pierdut sau furat`, `Actualizarea de la distanță a sistemului de operare`, `Conectarea la un desktop de la distanță`, `Curățarea cache-ului browser-ului`],
    correctIndex: 0,
    explanation: `Atunci când un dispozitiv este pierdut sau furat, Remote Wipe permite organizației să șteargă datele de la distanță pentru a proteja informațiile sensibile.`,
  },
  {
    id: `devices-131`,
    type: "single",
    topic: `General`,
    prompt: `BitLocker poate fi activat pe Windows 10 Home Edition. Adevărat sau Fals?`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — BitLocker este disponibil exclusiv pe edițiile Pro, Enterprise și Education; Home Edition nu îl include.`,
  },
  {
    id: `devices-132`,
    type: "single",
    topic: `General`,
    prompt: `Pentru criptarea automată cu BitLocker este necesar un anumit cip hardware. Care este acela?`,
    options: [`GPU`, `BIOS`, `TPM (Trusted Platform Module)`, `SSD Controller`],
    correctIndex: 2,
    explanation: `TPM este un cip de pe placa de bază care păstrează cheile criptografice în siguranță; BitLocker se integrează optim cu TPM.`,
  },
  {
    id: `devices-133`,
    type: "single",
    topic: `General`,
    prompt: `Ce reprezintă BitLocker To Go?`,
    options: [`Versiunea mobilă de BitLocker pentru telefoane`, `BitLocker pentru criptarea drive-urilor USB/externe`, `Un serviciu cloud de criptare`, `Un tool de backup`],
    correctIndex: 1,
    explanation: `BitLocker To Go aplică criptare pe medii portabile (stick-uri USB, HDD-uri externe), apărând datele în cazul în care dispozitivul este pierdut.`,
  },
  {
    id: `devices-134`,
    type: "single",
    topic: `General`,
    prompt: `Operațiunea System Restore șterge fișierele personale ale utilizatorului. Adevărat sau Fals?`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — System Restore aduce înapoi un punct de restaurare care afectează doar setări de sistem, drivere și programe, lăsând fișierele personale neatinse.`,
  },
  {
    id: `devices-135`,
    type: "single",
    topic: `General`,
    prompt: `Ce realizează opțiunea 'Reset this PC — Keep my files'?`,
    options: [`Revine la un restore point`, `Reinstalează Windows, păstrează fișierele personale, dar șterge aplicațiile instalate`, `Șterge tot de pe PC inclusiv fișierele`, `Face un backup al fișierelor în cloud`],
    correctIndex: 1,
    explanation: `Această variantă reinstalează Windows-ul de la zero, păstrând documentele personale, dar înlăturând aplicațiile, care vor trebui reinstalate.`,
  },
  {
    id: `devices-136`,
    type: "single",
    topic: `General`,
    prompt: `Ce realizează opțiunea 'Reset this PC — Remove everything'?`,
    options: [`Doar dezinstalează aplicațiile`, `Reinstalează Windows și șterge absolut tot — fișiere, aplicații, setări`, `Face un factory reset doar al BIOS-ului`, `Revine la versiunea anterioară de Windows`],
    correctIndex: 1,
    explanation: `Variantă echivalentă cu o resetare la valori de fabrică: Windows este reinstalat, iar toate fișierele, aplicațiile și setările dispar. Folosită înainte de a vinde sau ceda calculatorul.`,
  },
  {
    id: `devices-137`,
    type: "single",
    topic: `General`,
    prompt: `Un driver instalat recent provoacă blue screen, dar vrei să nu pierzi nimic. Ce variantă de recovery alegi?`,
    options: [`Reset this PC — Remove everything`, `System Restore to a previous restore point`, `Reset this PC — Keep my files`, `Fresh install de Windows`],
    correctIndex: 1,
    explanation: `Cu System Restore te întorci la momentul de dinaintea instalării driverului problematic, păstrând atât fișierele, cât și aplicațiile.`,
  },
  {
    id: `devices-138`,
    type: "single",
    topic: `General`,
    prompt: `Ce semnificație are 'Map a network drive'?`,
    options: [`Scanarea rețelei pentru viruși`, `Atribuirea unei litere de drive unui folder partajat din rețea (ex: Z:\\)`, `Configurarea unei rețele VPN`, `Instalarea unui driver de rețea`],
    correctIndex: 1,
    explanation: `Această operațiune asociază un share de rețea (ex: \\\\server\\share) cu o literă de unitate (Z:), oferind acces rapid din This PC fără a tasta calea de fiecare dată.`,
  },
  {
    id: `devices-139`,
    type: "single",
    topic: `General`,
    prompt: `În cazul unui conflict între o Local Policy și o Group Policy, care primează?`,
    options: [`Local Policy`, `Group Policy`, `Depinde de utilizator`, `Se anulează reciproc`],
    correctIndex: 1,
    explanation: `Group Policy distribuită prin Active Directory câștigă întotdeauna. Ordinea de aplicare este Local, apoi Site, Domain și OU; ultima setare aplicată se impune.`,
  },
  {
    id: `devices-140`,
    type: "single",
    topic: `General`,
    prompt: `Local Security Policy se aplică exclusiv pe calculatorul curent. Adevărat sau Fals?`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `Adevărat — Local Policy are efect doar pe acel PC, în timp ce Group Policy din Active Directory este distribuită tuturor calculatoarelor membre ale domeniului.`,
  },
  {
    id: `devices-141`,
    type: "single",
    topic: `General`,
    prompt: `În Event Viewer, ce indică un eveniment marcat printr-un cerc roșu?`,
    options: [`Information — eveniment normal`, `Warning — potențială problemă`, `Error — problemă serioasă`, `Audit success`],
    correctIndex: 2,
    explanation: `Roșul corespunde Error (eroare gravă, ceva nu a funcționat). Galbenul indică Warning, iar albastrul Information (totul în ordine).`,
  },
  {
    id: `devices-142`,
    type: "single",
    topic: `General`,
    prompt: `În Event Viewer, un eveniment Warning (triunghi galben) arată că sistemul s-a oprit. Adevărat sau Fals?`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `Fals — un Warning semnalează o posibilă problemă, însă sistemul continuă să funcționeze. Este un avertisment, nu o eroare critică.`,
  },
  {
    id: `devices-143`,
    type: "single",
    topic: `General`,
    prompt: `În care log din Event Viewer găsești evidența logărilor reușite și eșuate ale utilizatorilor?`,
    options: [`Application log`, `System log`, `Security log`, `Setup log`],
    correctIndex: 2,
    explanation: `Security log centralizează autentificările, accesările de fișiere și schimbările de permisiuni. Application acoperă programele, iar System acoperă Windows și driverele.`,
  },
  {
    id: `devices-144`,
    type: "single",
    topic: `General`,
    prompt: `Un driver de placă video provoacă erori la pornirea Windows-ului. În ce log din Event Viewer urmează să găsești înregistrările?`,
    options: [`Application`, `Security`, `System`, `Forwarded Events`],
    correctIndex: 2,
    explanation: `System log captează evenimentele asociate driverelor, serviciilor și componentelor sistem. Driverele aparțin sistemului, nu sunt aplicații, prin urmare nu apar în Application log.`,
  },
];
