// AUTO-GENERATED from scripts/questions.normalized.json — do not edit by hand.
// Re-run `node scripts/generate-question-modules.mjs` after extracting fresh content.

import type { Question } from "../types";

export const questions: readonly Question[] = [
  {
    id: `devices-001`,
    type: "single",
    topic: `General`,
    prompt: `Potrivește serviciul cu descrierea: 'A collection of cloud-based productivity apps'`,
    options: [`OneNote`, `Microsoft 365`, `SharePoint`, `Windows 365`],
    correctIndex: 1,
    explanation: `Microsoft 365 include Word, Excel, PowerPoint etc. în cloud.`,
  },
  {
    id: `devices-002`,
    type: "single",
    topic: `General`,
    prompt: `Potrivește serviciul cu descrierea: 'Works like a binder with tabs separating sections and pages'`,
    options: [`Microsoft 365`, `SharePoint`, `OneNote`, `Windows 365`],
    correctIndex: 2,
    explanation: `OneNote e organizat ca un caiet cu secțiuni și pagini.`,
  },
  {
    id: `devices-003`,
    type: "single",
    topic: `General`,
    prompt: `Potrivește serviciul cu descrierea: 'Used for storing documents for collaboration across an organization'`,
    options: [`OneNote`, `Windows 365`, `Microsoft 365`, `SharePoint`],
    correctIndex: 3,
    explanation: `SharePoint = platformă de stocare și colaborare pentru firme.`,
  },
  {
    id: `devices-004`,
    type: "single",
    topic: `General`,
    prompt: `Potrivește serviciul cu descrierea: 'Can be used to run an operating system and is accessible from Windows, MacOS, or ChromeOS'`,
    options: [`Windows 365`, `SharePoint`, `Microsoft 365`, `OneNote`],
    correctIndex: 0,
    explanation: `Windows 365 = PC virtual în cloud, accesibil de oriunde.`,
  },
  {
    id: `devices-005`,
    type: "single",
    topic: `General`,
    prompt: `In which settings can you find monitor resolution and refresh rate?`,
    options: [`Advanced display`, `Accessibility`, `Gaming`, `Device Manager`],
    correctIndex: 0,
    explanation: `Settings > System > Display > Advanced display settings.`,
  },
  {
    id: `devices-006`,
    type: "single",
    topic: `General`,
    prompt: `Microsoft Word crashes. Which Event Viewer log should you check for errors?`,
    options: [`Security`, `System`, `Application`, `Setup`],
    correctIndex: 2,
    explanation: `Word e o aplicație → erorile apar în Application log.`,
  },
  {
    id: `devices-007`,
    type: "single",
    topic: `General`,
    prompt: `Fișiere criptate + cu permisiuni de pe NTFS sunt copiate pe FAT32. Ce se întâmplă?`,
    options: [`Files still have permissions, encryption lost`, `Files lost their permissions and encryption`, `Files retained both encryption and permissions`, `Files are still encrypted, but permissions were lost`],
    correctIndex: 1,
    explanation: `FAT32 nu suportă nici criptare EFS, nici NTFS permissions. Ambele se pierd.`,
  },
  {
    id: `devices-008`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Third-party application installers cannot make changes to the Windows Registry'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — aproape orice installer scrie în Registry.`,
  },
  {
    id: `devices-009`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Deleting the shortcut for a third-party application will automatically uninstall the application'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — un shortcut e doar o legătură, programul rămâne instalat.`,
  },
  {
    id: `devices-010`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'By default, third-party apps are installed to different directories based on their architecture'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — 32-bit → Program Files (x86), 64-bit → Program Files.`,
  },
  {
    id: `devices-011`,
    type: "single",
    topic: `General`,
    prompt: `Windows 10 Home. Ce tip de cont creezi ca să-l folosești pe mai multe dispozitive Windows și cu serviciile Microsoft?`,
    options: [`Microsoft Account`, `Domain Account`, `Local Administrator Account`, `Local Standard Account`],
    correctIndex: 0,
    explanation: `Doar Microsoft Account se sincronizează între dispozitive.`,
  },
  {
    id: `devices-012`,
    type: "single",
    topic: `General`,
    prompt: `What type of data is primarily stored in the Windows Registry?`,
    options: [`Profiles and application settings`, `Audio and video files`, `Microsoft 365 documents`, `HTTP cookies`],
    correctIndex: 0,
    explanation: `Registry = bază de date cu configurări de profil și aplicații.`,
  },
  {
    id: `devices-013`,
    type: "single",
    topic: `General`,
    prompt: `Which Windows feature displays a consent prompt when a user attempts to install software?`,
    options: [`Active Directory (AD)`, `Windows Hello`, `User Account Control (UAC)`, `Windows Defender`],
    correctIndex: 2,
    explanation: `UAC afișează 'Do you want to allow this app to make changes?'`,
  },
  {
    id: `devices-014`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Graphics cards render the images in a computer and display them on the monitor'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — exact asta fac plăcile grafice.`,
  },
  {
    id: `devices-015`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'VGA, DVI, HDMI, and DisplayPort are all graphics card outputs'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — toate sunt porturi de ieșire video.`,
  },
  {
    id: `devices-016`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Integrated graphics cards have their own built-in memory'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — plăcile integrate folosesc RAM-ul sistemului, nu au VRAM propriu.`,
  },
  {
    id: `devices-017`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Graphics cards can access peripherals to help the CPU with processing speed'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — GPU-urile sunt specializate pe grafică, nu accesează periferice.`,
  },
  {
    id: `devices-018`,
    type: "single",
    topic: `General`,
    prompt: `USB printer conflict — nu găsești Printers folder în Device Manager. Care e problema?`,
    options: [`A printer conflict exists`, `Windows 10 does not support multiple printers`, `The USB port is broken`, `The printer driver is missing`],
    correctIndex: 0,
    explanation: `Instalarea imprimantei wireless a creat un conflict cu driverul USB.`,
  },
  {
    id: `devices-019`,
    type: "single",
    topic: `General`,
    prompt: `USB printer conflict — What should you do to further troubleshoot?`,
    options: [`Click Add legacy hardware on the Action menu`, `Click Show hidden devices on the View menu`, `Reinstall Windows`, `Run Windows Update`],
    correctIndex: 1,
    explanation: `View > Show hidden devices face vizibile dispozitivele ascunse/în conflict.`,
  },
  {
    id: `devices-020`,
    type: "single",
    topic: `General`,
    prompt: `Desktop config — Can the 'Logo on the Start button' be locally configured?`,
    options: [`Yes`, `No`],
    correctIndex: 1,
    explanation: `No — logo-ul Windows nu poate fi schimbat.`,
  },
  {
    id: `devices-021`,
    type: "single",
    topic: `General`,
    prompt: `Desktop config — Can the 'Taskbar location' be locally configured?`,
    options: [`Yes`, `No`],
    correctIndex: 0,
    explanation: `Yes — poți muta taskbar-ul pe orice margine a ecranului.`,
  },
  {
    id: `devices-022`,
    type: "single",
    topic: `General`,
    prompt: `Desktop config — Can 'Display resolution and orientation' be locally configured?`,
    options: [`Yes`, `No`],
    correctIndex: 0,
    explanation: `Yes — din Settings > Display.`,
  },
  {
    id: `devices-023`,
    type: "single",
    topic: `General`,
    prompt: `Desktop config — Can 'Folders that appear in the Start menu' be locally configured?`,
    options: [`Yes`, `No`],
    correctIndex: 0,
    explanation: `Yes — din Settings > Personalization > Start.`,
  },
  {
    id: `devices-024`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Driver updates can include non-Microsoft and manufacturer-installed drivers'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — Windows Update livrează și drivere de la NVIDIA, Intel etc.`,
  },
  {
    id: `devices-025`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Feature updates sometimes address security vulnerabilities'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — feature updates includ și patch-uri de securitate.`,
  },
  {
    id: `devices-026`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Service packs are a collection of updates, patches, and hot fixes'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — un Service Pack grupează toate update-urile.`,
  },
  {
    id: `devices-027`,
    type: "single",
    topic: `General`,
    prompt: `Ce permisiune NTFS îți permite să creezi un subfolder?`,
    options: [`Read`, `Read & Execute`, `Write`, `Full Control`],
    correctIndex: 2,
    explanation: `Write îți dă dreptul să creezi fișiere/foldere noi.`,
  },
  {
    id: `devices-028`,
    type: "single",
    topic: `General`,
    prompt: `Ce permisiune NTFS îți permite să ștergi un subfolder?`,
    options: [`Read`, `Write`, `Read & Execute`, `Full Control`],
    correctIndex: 3,
    explanation: `Full Control include dreptul de ștergere.`,
  },
  {
    id: `devices-029`,
    type: "single",
    topic: `General`,
    prompt: `Ce permisiune NTFS îți permite să rulezi o aplicație?`,
    options: [`Write`, `Read & Execute`, `Full Control`, `Read`],
    correctIndex: 1,
    explanation: `Read & Execute = poți citi și rula un .exe.`,
  },
  {
    id: `devices-030`,
    type: "single",
    topic: `General`,
    prompt: `Potrivește malware: 'Replicates itself, can be spread by email attachments'`,
    options: [`Logic Bomb`, `Ransomware`, `Trojan Horse`, `Worm`],
    correctIndex: 3,
    explanation: `Worm = se replică singur și se răspândește prin email.`,
  },
  {
    id: `devices-031`,
    type: "single",
    topic: `General`,
    prompt: `Potrivește malware: 'Causes data inaccessibility until demands are met'`,
    options: [`Worm`, `Ransomware`, `Logic Bomb`, `Trojan Horse`],
    correctIndex: 1,
    explanation: `Ransomware = criptează datele și cere răscumpărare.`,
  },
  {
    id: `devices-032`,
    type: "single",
    topic: `General`,
    prompt: `Potrivește malware: 'Malicious software that appears to be a legitimate program'`,
    options: [`Worm`, `Logic Bomb`, `Trojan Horse`, `Ransomware`],
    correctIndex: 2,
    explanation: `Trojan Horse = pare un program normal dar e malware.`,
  },
  {
    id: `devices-033`,
    type: "single",
    topic: `General`,
    prompt: `Potrivește malware: 'Piece of code triggered by a condition, can cause damage'`,
    options: [`Logic Bomb`, `Worm`, `Ransomware`, `Trojan Horse`],
    correctIndex: 0,
    explanation: `Logic Bomb = se activează doar când se îndeplinește o condiție.`,
  },
  {
    id: `devices-034`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Domain administrators have complete access to files, directories, and services on the local server'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — Domain Admin = control total pe serverele din domeniu.`,
  },
  {
    id: `devices-035`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Domain administrators can create domain users and assign rights to those users'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — gestionarea utilizatorilor e funcția principală.`,
  },
  {
    id: `devices-036`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Domain administrators are prevented from lockouts'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — pot fi blocați. Doar built-in Administrator nu se blochează.`,
  },
  {
    id: `devices-037`,
    type: "single",
    topic: `General`,
    prompt: `In Task Manager, which tab should you use to end a program that is not responding?`,
    options: [`App history`, `Performance`, `Startup apps`, `Processes`],
    correctIndex: 3,
    explanation: `Processes → click dreapta → End Task.`,
  },
  {
    id: `devices-038`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Restarting your computer will wipe the RAM storage'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — RAM e volatilă, se golește la restart.`,
  },
  {
    id: `devices-039`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Opening a program loads the application into RAM'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — programele se încarcă de pe disc în RAM.`,
  },
  {
    id: `devices-040`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Reading data from RAM is slower than reading data from the hard disk drive'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — RAM e de zeci de mii de ori mai rapid decât HDD.`,
  },
  {
    id: `devices-041`,
    type: "single",
    topic: `General`,
    prompt: `True or False: '64-bit applications are installed in C:\Program Files (x86) by default'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — (x86) e pentru 32-bit. 64-bit → Program Files (fără x86).`,
  },
  {
    id: `devices-042`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Deleting an application folder uninstalls it and removes registry settings'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — ștergerea manuală NU curăță Registry. Folosește uninstaller.`,
  },
  {
    id: `devices-043`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'A UAC prompt displays when Standard Users install apps in Program Files'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — Program Files e protejat, necesită permisiuni admin.`,
  },
  {
    id: `devices-044`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'A Microsoft account is necessary to configure facial recognition'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — Windows Hello funcționează și cu cont local.`,
  },
  {
    id: `devices-045`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'A compatible infrared (IR) camera is needed to set up facial recognition'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — Windows Hello Face necesită cameră IR specială.`,
  },
  {
    id: `devices-046`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'If facial recognition fails, the user will be automatically logged in with the saved password'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — trebuie să introduci manual PIN-ul sau parola.`,
  },
  {
    id: `devices-047`,
    type: "single",
    topic: `General`,
    prompt: `File server FS1, share 'Training' — Can you open a subfolder at \\FS1\Training?`,
    options: [`Yes`, `No`],
    correctIndex: 0,
    explanation: `Yes — ai permisiuni de Read prin share.`,
  },
  {
    id: `devices-048`,
    type: "single",
    topic: `General`,
    prompt: `File server FS1, share 'Training' — Can you create a subfolder at \\FS1\Training?`,
    options: [`Yes`, `No`],
    correctIndex: 1,
    explanation: `No — share permissions restricționează crearea.`,
  },
  {
    id: `devices-049`,
    type: "single",
    topic: `General`,
    prompt: `File server FS1 — Can you create a subfolder at D:\Projects\Training if you remote into FS1?`,
    options: [`Yes`, `No`],
    correctIndex: 1,
    explanation: `No — NTFS permissions nu îți permit Write.`,
  },
  {
    id: `devices-050`,
    type: "single",
    topic: `General`,
    prompt: `Active Directory: 'It allows users to use their credentials throughout the network'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — AD = Single Sign-On pe toată rețeaua.`,
  },
  {
    id: `devices-051`,
    type: "single",
    topic: `General`,
    prompt: `Active Directory: 'It allows efficient searching of files on your computer'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — AD gestionează utilizatori, nu caută fișiere (asta e Windows Search).`,
  },
  {
    id: `devices-052`,
    type: "single",
    topic: `General`,
    prompt: `Active Directory: 'It allows all users to configure their own rights'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — doar administratorii configurează drepturi.`,
  },
  {
    id: `devices-053`,
    type: "single",
    topic: `General`,
    prompt: `PC-ul nu aplică noile Group Policy de securitate. Trebuie să forțezi refresh. Ce faci?`,
    options: [`Run gpupdate /force from command prompt`, `Open Local Security Policy and choose Reload`, `Run gpresult /h from command prompt`, `Open System Information and Refresh`],
    correctIndex: 0,
    explanation: `gpupdate /force reaplică toate politicile. gpresult doar arată politicile.`,
  },
  {
    id: `devices-054`,
    type: "single",
    topic: `General`,
    prompt: `Windows Defender a pus în carantină un program. IT confirmă că e fals pozitiv. Ce faci?`,
    options: [`Find and delete the file in Windows Explorer`, `Reinstall the program`, `Run the scan again`, `Recover the file from quarantine`],
    correctIndex: 3,
    explanation: `Programul e safe → îl recuperezi din carantină.`,
  },
  {
    id: `devices-055`,
    type: "single",
    topic: `General`,
    prompt: `Imprimantă legacy prin USB-to-serial. Trebuie să schimbi baud rate, data bits, parity. Ce categorie din Device Manager?`,
    options: [`Printers`, `Print queues`, `Ports (COM & LPT)`, `Storage controllers`],
    correctIndex: 2,
    explanation: `Setările seriale se configurează în Ports (COM & LPT).`,
  },
  {
    id: `devices-056`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'A computer's max supported RAM capacity and speed are determined by the motherboard'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — motherboard-ul dictează RAM max și viteza suportată.`,
  },
  {
    id: `devices-057`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'You can upgrade an Intel processor to AMD without changing the motherboard'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — Intel și AMD au socket-uri diferite, trebuie schimbat MB.`,
  },
  {
    id: `devices-058`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'BIOS settings are stored on the motherboard'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — BIOS e pe un chip de pe motherboard, păstrat de bateria CMOS.`,
  },
  {
    id: `devices-059`,
    type: "single",
    topic: `General`,
    prompt: `Un user vrea să partajeze ecranul pe un smart TV wireless. Unde în System settings?`,
    options: [`Nearby sharing`, `Display`, `Projecting to this PC`, `Remote Desktop`],
    correctIndex: 1,
    explanation: `Settings > System > Display — conectezi wireless display (Miracast).`,
  },
  {
    id: `devices-060`,
    type: "single",
    topic: `General`,
    prompt: `SSID-ul rețelei e vizibil dar nimeni nu se poate conecta. Ce faci?`,
    options: [`Execute ipconfig /renew`, `Check each employee's Ethernet cable`, `Reboot the access point or router`, `Verify that Wi-Fi is enabled`],
    correctIndex: 2,
    explanation: `Dacă toți văd rețeaua dar nimeni nu se conectează → reboot router.`,
  },
  {
    id: `devices-061`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Setting up a new drive is done through Disk Management'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — Disk Management = inițializare, partiționare, formatare.`,
  },
  {
    id: `devices-062`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Freeing up disk space for a slow computer is done through Disk Management'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — se face prin Disk Cleanup, NU Disk Management!`,
  },
  {
    id: `devices-063`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Manually updating drivers can be done through the Device Manager'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — click dreapta pe dispozitiv > Update driver.`,
  },
  {
    id: `devices-064`,
    type: "single",
    topic: `General`,
    prompt: `USB 4GB, compatibilitate maximă cu camere vechi, console, non-Windows. Ce file system?`,
    options: [`ExFAT`, `FAT16`, `NTFS`, `FAT32`],
    correctIndex: 3,
    explanation: `FAT32 = cel mai universal, funcționează pe orice dispozitiv.`,
  },
  {
    id: `devices-065`,
    type: "single",
    topic: `General`,
    prompt: `După upgrade la Win 10, spațiul pe disc a crescut. Vrei mai mult spațiu liber. Ce faci?`,
    options: [`Defragment the hard drive`, `Remove and reinstall all applications`, `Run Disk Cleanup to remove previous Windows installation(s)`, `Adjust system settings to allocate more space`],
    correctIndex: 2,
    explanation: `Disk Cleanup șterge Windows.old, eliberând 10-20+ GB.`,
  },
  {
    id: `devices-066`,
    type: "single",
    topic: `General`,
    prompt: `Windows Backup: 'Can be used to back up files and folders to the cloud'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — Windows Backup face backup în OneDrive (cloud).`,
  },
  {
    id: `devices-067`,
    type: "single",
    topic: `General`,
    prompt: `Windows Backup: 'Can be used to back up saved passwords and credentials'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — salvează și credențialele.`,
  },
  {
    id: `devices-068`,
    type: "single",
    topic: `General`,
    prompt: `Windows Backup: 'Can be used to back up files and folders to physical media'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — Windows Backup (nou) = cloud. Pentru disc extern → Backup and Restore.`,
  },
  {
    id: `devices-069`,
    type: "single",
    topic: `General`,
    prompt: `Unde configurezi setările Narrator în Windows 10?`,
    options: [`Apps`, `Accessibility`, `Ease of Access`, `Personalization`],
    correctIndex: 2,
    explanation: `Narrator = accesibilitate → Settings > Ease of Access.`,
  },
  {
    id: `devices-070`,
    type: "single",
    topic: `General`,
    prompt: `User nu se conectează la rețea. Trebuie IP-ul și default gateway. Ce comandă?`,
    options: [`ipconfig`, `ping 0.0.0.0`, `ipconfig /release`, `ping 127.0.0.1`],
    correctIndex: 0,
    explanation: `ipconfig arată IP, subnet mask, default gateway.`,
  },
  {
    id: `devices-071`,
    type: "single",
    topic: `General`,
    prompt: `Backup automat D:\Books la fiecare 10 min, fără internet, restore versiuni anterioare. Ce faci?`,
    options: [`Configure System Restore`, `Configure OneDrive to sync`, `Use Backup and Restore to create a system image`, `Enable File History to save copies to a network drive`],
    correctIndex: 3,
    explanation: `File History = backup-uri regulate pe drive extern, cu versiuni anterioare.`,
  },
  {
    id: `devices-072`,
    type: "single",
    topic: `General`,
    prompt: `Instalezi Win 10 pe PC nou cu un singur hard drive. Cum pregătești media de instalare?`,
    options: [`Run Media Creation tool on internal hard drive`, `Copy Windows 10 ISO to a USB drive`, `Copy Windows 10 ISO to internal hard drive`, `Run Media Creation tool on a USB drive`],
    correctIndex: 3,
    explanation: `Media Creation Tool creează USB bootabil. Nu poți instala de pe drive-ul țintă.`,
  },
  {
    id: `devices-073`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de cont ai nevoie pentru a gestiona fișiere de sistem pe Windows 10 Home?`,
    options: [`Administrator User Account`, `Standard User Account`, `Domain User Account`, `Microsoft Account`],
    correctIndex: 0,
    explanation: `Fișierele de sistem sunt protejate — doar Administrator le poate modifica.`,
  },
  {
    id: `devices-074`,
    type: "single",
    topic: `General`,
    prompt: `Nu poți instala o aplicație din Microsoft Store. Ce tool folosești?`,
    options: [`Device Manager`, `Installed Apps`, `WSReset.exe`, `Task Manager`],
    correctIndex: 2,
    explanation: `WSReset.exe resetează cache-ul Microsoft Store.`,
  },
  {
    id: `devices-075`,
    type: "single",
    topic: `General`,
    prompt: `Formatezi un SSD de 3TB pentru Win 10, reduce data loss. Alege formatul:`,
    options: [`NTFS`, `FAT32`, `exFAT`, `FAT16`],
    correctIndex: 0,
    explanation: `NTFS = robust, suportă permisiuni și criptare.`,
  },
  {
    id: `devices-076`,
    type: "single",
    topic: `General`,
    prompt: `Formatezi un SSD de 3TB pentru Win 10, reduce data loss. Alege stilul de partiție:`,
    options: [`MBR`, `GPT`],
    correctIndex: 1,
    explanation: `GPT pentru discuri >2TB + are backup la tabela de partiții.`,
  },
  {
    id: `devices-077`,
    type: "single",
    topic: `General`,
    prompt: `Windows Registry: 'Settings are persistent across system restarts'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — Registry e pe disc, nu se pierde la restart.`,
  },
  {
    id: `devices-078`,
    type: "single",
    topic: `General`,
    prompt: `Windows Registry: 'Application installers can modify the registry'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — installerele scriu în Registry.`,
  },
  {
    id: `devices-079`,
    type: "single",
    topic: `General`,
    prompt: `Windows Registry: 'Changes to settings are immediately backed up to OneDrive'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — Registry e local, nu se sincronizează cu OneDrive.`,
  },
  {
    id: `devices-080`,
    type: "single",
    topic: `General`,
    prompt: `Windows Update: 'Optional updates are accessible directly from Windows Update Advanced Options'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — Advanced Options > Optional updates.`,
  },
  {
    id: `devices-081`,
    type: "single",
    topic: `General`,
    prompt: `Windows Update: 'Uninstall for recently installed updates can be accessed under update history'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — Update History > Uninstall updates.`,
  },
  {
    id: `devices-082`,
    type: "single",
    topic: `General`,
    prompt: `Windows Update: 'Required updates pending will only install when active hours are set'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — update-urile se instalează și în afara active hours.`,
  },
  {
    id: `devices-083`,
    type: "single",
    topic: `General`,
    prompt: `Conector: 'Can deliver both power and data to a device'`,
    options: [`USB Type-C`, `VGA`, `DisplayPort`, `HDMI`],
    correctIndex: 0,
    explanation: `USB-C = curent + date prin același cablu.`,
  },
  {
    id: `devices-084`,
    type: "single",
    topic: `General`,
    prompt: `Conector: 'Typically found on legacy monitors and computers'`,
    options: [`HDMI`, `USB Type-C`, `VGA`, `DisplayPort`],
    correctIndex: 2,
    explanation: `VGA = din 1987, cel mai vechi, pe dispozitive legacy.`,
  },
  {
    id: `devices-085`,
    type: "single",
    topic: `General`,
    prompt: `Conector: 'Used by monitors and computers, but NOT game consoles'`,
    options: [`HDMI`, `VGA`, `DisplayPort`, `USB Type-C`],
    correctIndex: 2,
    explanation: `DisplayPort = standard pe monitoare PC, consolele au HDMI.`,
  },
  {
    id: `devices-086`,
    type: "single",
    topic: `General`,
    prompt: `Conector: 'Used by televisions, computers, game consoles, and projectors'`,
    options: [`VGA`, `DisplayPort`, `USB Type-C`, `HDMI`],
    correctIndex: 3,
    explanation: `HDMI = cel mai universal — TV, PC, console, proiectoare.`,
  },
  {
    id: `devices-087`,
    type: "single",
    topic: `General`,
    prompt: `What is the primary function of the Windows Registry?`,
    options: [`Verifies the integrity of files on the hard drive`, `Indexes data in the file system to improve searching`, `Stores data for profiles, applications, and hardware drivers`, `Provides protection from malicious software`],
    correctIndex: 2,
    explanation: `Registry = bază de date centrală cu configurări.`,
  },
  {
    id: `devices-088`,
    type: "single",
    topic: `General`,
    prompt: `Smartphone conectat prin USB nu e recunoscut. Trebuie cel mai recent driver. Ce configurezi?`,
    options: [`Phone and Modem`, `System Configuration`, `Device Manager`, `Windows Mobility Center`],
    correctIndex: 2,
    explanation: `Device Manager = actualizare/instalare drivere.`,
  },
  {
    id: `devices-089`,
    type: "single",
    topic: `General`,
    prompt: `Drivers: 'Windows not finding a new driver means there is not an updated driver available'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — producătorul poate avea un driver mai nou pe site.`,
  },
  {
    id: `devices-090`,
    type: "single",
    topic: `General`,
    prompt: `Drivers: 'Before reinstalling a driver, uninstall the driver then restart the PC'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — best practice: uninstall > restart > reinstall.`,
  },
  {
    id: `devices-091`,
    type: "single",
    topic: `General`,
    prompt: `Drivers: 'Windows will allow a driver to be rolled back to any previous version'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — Roll Back revine doar la versiunea imediat anterioară.`,
  },
  {
    id: `devices-092`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de date transmite DisplayPort?`,
    options: [`Audio`, `Video`, `Audio & Video`],
    correctIndex: 2,
    explanation: `DisplayPort = audio + video.`,
  },
  {
    id: `devices-093`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de date transmite VGA?`,
    options: [`Audio`, `Video`, `Audio & Video`],
    correctIndex: 1,
    explanation: `VGA = doar video (analog, fără sunet).`,
  },
  {
    id: `devices-094`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de date transmite HDMI?`,
    options: [`Audio`, `Video`, `Audio & Video`],
    correctIndex: 2,
    explanation: `HDMI = audio + video.`,
  },
  {
    id: `devices-095`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de date transmite S/PDIF Optical?`,
    options: [`Audio`, `Video`, `Audio & Video`],
    correctIndex: 0,
    explanation: `S/PDIF = doar audio digital (fibră optică).`,
  },
  {
    id: `devices-096`,
    type: "single",
    topic: `General`,
    prompt: `Authenticator: 'Can send push notifications for both local and Microsoft accounts'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — doar pentru Microsoft/Azure AD, NU conturi locale.`,
  },
  {
    id: `devices-097`,
    type: "single",
    topic: `General`,
    prompt: `Authenticator: 'You can use it to login if you forget your password'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — e al doilea factor (2FA), nu înlocuiește parola.`,
  },
  {
    id: `devices-098`,
    type: "single",
    topic: `General`,
    prompt: `Authenticator: 'Generates time-based one-time passwords as part of MFA'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — generează coduri TOTP (se schimbă la 30 secunde).`,
  },
  {
    id: `devices-099`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'RAM is non-volatile'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — RAM e VOLATILĂ (pierde tot la oprirea curentului).`,
  },
  {
    id: `devices-100`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'A low latency HDD is faster than an SSD'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — niciun HDD nu e mai rapid decât un SSD.`,
  },
  {
    id: `devices-101`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'Physical storage includes SSD, HDD, and flash drives'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — toate sunt dispozitive fizice de stocare.`,
  },
  {
    id: `devices-102`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'NTFS supports a maximum file size of 4GB'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — asta e limita FAT32! NTFS suportă până la 16TB.`,
  },
  {
    id: `devices-103`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'FAT32 supports partitions up to 32TB'`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — FAT32 max ~2TB. 32TB e exagerat.`,
  },
  {
    id: `devices-104`,
    type: "single",
    topic: `General`,
    prompt: `True or False: 'ExFAT is ideal for flash drives and supports storage media up to 256TB'`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — ExFAT = creat pentru flash drives, fără limita de 4GB.`,
  },
  {
    id: `devices-105`,
    type: "single",
    topic: `General`,
    prompt: `Un utilizator se conectează la Wi-Fi într-o cafenea. Ce tip de network profile ar trebui selectat în Windows?`,
    options: [`Private`, `Public`, `Domain`, `Guest`],
    correctIndex: 1,
    explanation: `Public network = locuri publice (cafenea, aeroport). PC-ul nu e vizibil, partajarea e dezactivată, firewall-ul e mai restrictiv.`,
  },
  {
    id: `devices-106`,
    type: "single",
    topic: `General`,
    prompt: `Pe o rețea Private, PC-ul este vizibil celorlalte dispozitive din rețea. True or False?`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — Private = acasă/birou. PC-ul e vizibil, file sharing și printer sharing sunt permise.`,
  },
  {
    id: `devices-107`,
    type: "single",
    topic: `General`,
    prompt: `Ce se întâmplă dacă dezactivezi Windows Defender Firewall?`,
    options: [`Windows Update nu mai funcționează`, `PC-ul devine vulnerabil la accesul neautorizat din rețea`, `Antivirusul Windows Defender se dezactivează automat`, `Nu mai poți accesa internetul`],
    correctIndex: 1,
    explanation: `Firewall-ul blochează conexiunile neautorizate. Fără el, PC-ul e expus atacurilor din rețea. Antivirusul e separat de firewall.`,
  },
  {
    id: `devices-108`,
    type: "single",
    topic: `General`,
    prompt: `Care este diferența principală între Private și Public network profile în Windows?`,
    options: [`Private necesită parolă, Public nu`, `Private permite file sharing și discovery, Public le blochează`, `Public e mai rapid decât Private`, `Private funcționează doar cu Ethernet`],
    correctIndex: 1,
    explanation: `Private = sharing ON, device discovery ON. Public = sharing OFF, device discovery OFF. E vorba de securitate, nu viteză.`,
  },
  {
    id: `devices-109`,
    type: "single",
    topic: `General`,
    prompt: `Rulezi ipconfig și vezi IP-ul 169.254.15.200. Ce indică acest lucru?`,
    options: [`IP static configurat manual`, `Conexiune VPN activă`, `PC-ul nu a putut obține un IP de la serverul DHCP`, `Adresa IP a routerului`],
    correctIndex: 2,
    explanation: `169.254.x.x = APIPA. Înseamnă că PC-ul nu a contactat un server DHCP și și-a auto-atribuit un IP. Nu ai acces la internet.`,
  },
  {
    id: `devices-110`,
    type: "single",
    topic: `General`,
    prompt: `Ce range de IP-uri folosește APIPA?`,
    options: [`192.168.x.x`, `10.0.x.x`, `169.254.x.x`, `172.16.x.x`],
    correctIndex: 2,
    explanation: `APIPA folosește întotdeauna 169.254.0.1 - 169.254.255.254. Celelalte sunt IP-uri private standard.`,
  },
  {
    id: `devices-111`,
    type: "single",
    topic: `General`,
    prompt: `Un PC are adresă APIPA (169.254.x.x). Care este cel mai probabil primul pas de troubleshooting?`,
    options: [`Reinstalează Windows`, `Verifică conexiunea la router/switch și dacă DHCP funcționează`, `Schimbă placa de rețea`, `Dezactivează firewall-ul`],
    correctIndex: 1,
    explanation: `APIPA = nu primești IP de la DHCP. Verifică cablul, routerul, și dacă serviciul DHCP e activ.`,
  },
  {
    id: `devices-112`,
    type: "single",
    topic: `General`,
    prompt: `Ce este Safe Mode în Windows?`,
    options: [`Un mod care criptează toate fișierele`, `Un mod de boot cu drivere și fișiere minime, pentru diagnostic`, `Un mod care blochează accesul la internet permanent`, `Un mod de backup automat`],
    correctIndex: 1,
    explanation: `Safe Mode pornește Windows cu minimum de drivere. Folosit pentru a diagnostica probleme — dacă PC-ul merge în Safe Mode, problema e de la un driver sau program.`,
  },
  {
    id: `devices-113`,
    type: "single",
    topic: `General`,
    prompt: `Care variantă de Safe Mode permite accesul la internet?`,
    options: [`Safe Mode`, `Safe Mode with Networking`, `Safe Mode with Command Prompt`, `Niciuna`],
    correctIndex: 1,
    explanation: `Safe Mode with Networking = Safe Mode + drivere de rețea, deci ai acces la internet pentru a descărca drivere/update-uri.`,
  },
  {
    id: `devices-114`,
    type: "single",
    topic: `General`,
    prompt: `Cum accesezi Advanced Startup Options pentru a intra în Safe Mode?`,
    options: [`Apasă F1 la pornire`, `Din Settings > Update & Security > Recovery > Restart now, sau Shift + Restart`, `Din Control Panel > System`, `Din Task Manager > Startup`],
    correctIndex: 1,
    explanation: `Settings > Update & Security > Recovery > Advanced startup > Restart now. Sau ții Shift apăsat și dai Restart.`,
  },
  {
    id: `devices-115`,
    type: "single",
    topic: `General`,
    prompt: `Safe Mode with Command Prompt oferă interfață grafică completă. True or False?`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — Safe Mode with Command Prompt nu afișează desktop-ul normal, doar o fereastră de command prompt. E pentru utilizatori avansați.`,
  },
  {
    id: `devices-116`,
    type: "single",
    topic: `General`,
    prompt: `Ce serviciu Microsoft oferă cloud storage integrat în Windows 10?`,
    options: [`SharePoint`, `OneDrive`, `Azure`, `Teams`],
    correctIndex: 1,
    explanation: `OneDrive = cloud storage personal integrat în Windows. SharePoint e pentru colaborare în organizații.`,
  },
  {
    id: `devices-117`,
    type: "single",
    topic: `General`,
    prompt: `Ce este OneDrive Files On-Demand?`,
    options: [`Fișierele sunt șterse automat după 30 de zile`, `Poți vedea fișierele din cloud fără să le descarci pe PC`, `Fișierele sunt criptate automat`, `Fișierele sunt partajate automat cu toți contactele`],
    correctIndex: 1,
    explanation: `Files On-Demand arată fișierele din cloud în File Explorer fără a ocupa spațiu pe disc. Se descarcă doar când le deschizi.`,
  },
  {
    id: `devices-118`,
    type: "single",
    topic: `General`,
    prompt: `Un fișier OneDrive marcat ca 'Always available on this device' este accesibil fără internet. True or False?`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — 'Always available' descarcă o copie locală pe PC. Poți lucra cu fișierul și offline.`,
  },
  {
    id: `devices-119`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de malware colectează informații despre utilizator fără consimțământul acestuia?`,
    options: [`Ransomware`, `Adware`, `Spyware`, `Logic Bomb`],
    correctIndex: 2,
    explanation: `Spyware = spy (spion). Colectează date (istoricul de browsing, parole, tastele apăsate) pe ascuns.`,
  },
  {
    id: `devices-120`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de atac folosește emailuri false care par de la o sursă legitimă pentru a fura date personale?`,
    options: [`Keylogger`, `Phishing`, `Adware`, `Worm`],
    correctIndex: 1,
    explanation: `Phishing = 'pescuit' de date. Emailuri false (par de la bancă, PayPal etc.) care cer parole sau date de card.`,
  },
  {
    id: `devices-121`,
    type: "single",
    topic: `General`,
    prompt: `Ce face un keylogger?`,
    options: [`Blochează tastatura`, `Înregistrează fiecare tastă apăsată de utilizator`, `Criptează fișierele`, `Afișează reclame`],
    correctIndex: 1,
    explanation: `Keylogger = key (tastă) + logger (înregistrător). Capturează tot ce tastezi — parole, mesaje, date bancare.`,
  },
  {
    id: `devices-122`,
    type: "single",
    topic: `General`,
    prompt: `Ce este social engineering în contextul securității IT?`,
    options: [`Un tip de criptare`, `Manipulare psihologică pentru a obține informații confidențiale`, `Un protocol de rețea`, `Un software antivirus`],
    correctIndex: 1,
    explanation: `Social engineering = atacatorul manipulează oameni (nu sisteme). Ex: se dă drept coleg IT și cere parola.`,
  },
  {
    id: `devices-123`,
    type: "single",
    topic: `General`,
    prompt: `Ce tip de malware afișează reclame nedorite pe computerul utilizatorului?`,
    options: [`Spyware`, `Trojan Horse`, `Adware`, `Ransomware`],
    correctIndex: 2,
    explanation: `Adware = ad (reclamă) + ware (software). Afișează pop-up-uri și reclame nedorite.`,
  },
  {
    id: `devices-124`,
    type: "single",
    topic: `General`,
    prompt: `Ce se întâmplă cu datele din RAM când PC-ul intră în Sleep mode?`,
    options: [`Sunt șterse complet`, `Sunt salvate pe hard disk`, `RAM rămâne alimentată, datele sunt păstrate`, `Sunt transferate în cloud`],
    correctIndex: 2,
    explanation: `Sleep = RAM rămâne alimentată cu puțin curent. Datele rămân în RAM, revenirea e instantanee. Dar dacă se pierde curentul, datele se pierd!`,
  },
  {
    id: `devices-125`,
    type: "single",
    topic: `General`,
    prompt: `Ce se întâmplă cu datele din RAM când PC-ul intră în Hibernate?`,
    options: [`RAM rămâne alimentată`, `Conținutul RAM-ului este salvat pe disc (hiberfil.sys), apoi PC-ul se oprește complet`, `Datele sunt șterse`, `Datele sunt trimise în cloud`],
    correctIndex: 1,
    explanation: `Hibernate = salvează tot din RAM pe disc → oprește complet PC-ul → consum zero. La pornire, restaurează totul de pe disc.`,
  },
  {
    id: `devices-126`,
    type: "single",
    topic: `General`,
    prompt: `Care power option consumă cel mai puțin curent?`,
    options: [`Sleep`, `Hibernate`, `Lock screen`, `Balanced mode`],
    correctIndex: 1,
    explanation: `Hibernate = consum zero (PC-ul e oprit complet). Sleep consumă puțin curent pentru a menține RAM-ul alimentat.`,
  },
  {
    id: `devices-127`,
    type: "single",
    topic: `General`,
    prompt: `Care este power plan-ul recomandat de Windows pentru majoritatea utilizatorilor?`,
    options: [`Power saver`, `High performance`, `Balanced`, `Ultimate performance`],
    correctIndex: 2,
    explanation: `Balanced = echilibru între performanță și consum de energie. E setarea implicită recomandată.`,
  },
  {
    id: `devices-128`,
    type: "single",
    topic: `General`,
    prompt: `Ce este MDM (Mobile Device Management)?`,
    options: [`Un protocol de rețea wireless`, `Software care permite companiilor să gestioneze dispozitivele mobile ale angajaților de la distanță`, `Un tip de criptare pentru telefoane`, `O aplicație de backup`],
    correctIndex: 1,
    explanation: `MDM = gestionare centralizată a telefoanelor/tabletelor. Compania poate impune parole, instala aplicații, și face remote wipe.`,
  },
  {
    id: `devices-129`,
    type: "single",
    topic: `General`,
    prompt: `Ce înseamnă BYOD?`,
    options: [`Back Your Own Data`, `Bring Your Own Device`, `Build Your Own Desktop`, `Backup Your Online Documents`],
    correctIndex: 1,
    explanation: `BYOD = Bring Your Own Device. Angajatul folosește dispozitivul personal la muncă. Compania poate impune politici de securitate.`,
  },
  {
    id: `devices-130`,
    type: "single",
    topic: `General`,
    prompt: `Ce este Remote Wipe?`,
    options: [`Ștergerea de la distanță a tuturor datelor de pe un dispozitiv pierdut sau furat`, `Actualizarea de la distanță a sistemului de operare`, `Conectarea la un desktop de la distanță`, `Curățarea cache-ului browser-ului`],
    correctIndex: 0,
    explanation: `Remote wipe = dacă telefonul e pierdut/furat, compania poate șterge toate datele de la distanță pentru a proteja informațiile.`,
  },
  {
    id: `devices-131`,
    type: "single",
    topic: `General`,
    prompt: `BitLocker este disponibil pe Windows 10 Home Edition. True or False?`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — BitLocker e disponibil DOAR pe Pro, Enterprise, și Education. Home Edition NU are BitLocker.`,
  },
  {
    id: `devices-132`,
    type: "single",
    topic: `General`,
    prompt: `Ce chip hardware necesită BitLocker pentru criptarea automată?`,
    options: [`GPU`, `BIOS`, `TPM (Trusted Platform Module)`, `SSD Controller`],
    correctIndex: 2,
    explanation: `TPM = chip pe motherboard care stochează cheile de criptare în siguranță. BitLocker funcționează cel mai bine cu TPM.`,
  },
  {
    id: `devices-133`,
    type: "single",
    topic: `General`,
    prompt: `Ce este BitLocker To Go?`,
    options: [`Versiunea mobilă de BitLocker pentru telefoane`, `BitLocker pentru criptarea drive-urilor USB/externe`, `Un serviciu cloud de criptare`, `Un tool de backup`],
    correctIndex: 1,
    explanation: `BitLocker To Go = criptare pentru dispozitive portabile (USB drives, HDD-uri externe). Protejează datele dacă pierzi stick-ul USB.`,
  },
  {
    id: `devices-134`,
    type: "single",
    topic: `General`,
    prompt: `System Restore șterge fișierele personale ale utilizatorului. True or False?`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — System Restore revine la un restore point anterior. Afectează DOAR setările de sistem, driverele și programele. Fișierele personale NU sunt atinse.`,
  },
  {
    id: `devices-135`,
    type: "single",
    topic: `General`,
    prompt: `Ce face opțiunea 'Reset this PC — Keep my files'?`,
    options: [`Revine la un restore point`, `Reinstalează Windows, păstrează fișierele personale, dar șterge aplicațiile instalate`, `Șterge tot de pe PC inclusiv fișierele`, `Face un backup al fișierelor în cloud`],
    correctIndex: 1,
    explanation: `Reset (Keep files) = Windows reinstalat fresh, fișierele rămân, dar toate aplicațiile sunt șterse (trebuie reinstalate).`,
  },
  {
    id: `devices-136`,
    type: "single",
    topic: `General`,
    prompt: `Ce face opțiunea 'Reset this PC — Remove everything'?`,
    options: [`Doar dezinstalează aplicațiile`, `Reinstalează Windows și șterge absolut tot — fișiere, aplicații, setări`, `Face un factory reset doar al BIOS-ului`, `Revine la versiunea anterioară de Windows`],
    correctIndex: 1,
    explanation: `Remove everything = PC-ul revine ca NOU. Tot ce era pe el dispare. Folosit când vinzi/dai PC-ul.`,
  },
  {
    id: `devices-137`,
    type: "single",
    topic: `General`,
    prompt: `Care opțiune de recovery ar trebui folosită dacă un driver nou cauzează blue screen, dar vrei să păstrezi tot?`,
    options: [`Reset this PC — Remove everything`, `System Restore to a previous restore point`, `Reset this PC — Keep my files`, `Fresh install de Windows`],
    correctIndex: 1,
    explanation: `System Restore = revii la starea de dinaintea instalării driverului problematic. Fișierele și aplicațiile rămân intacte.`,
  },
  {
    id: `devices-138`,
    type: "single",
    topic: `General`,
    prompt: `Ce înseamnă 'Map a network drive'?`,
    options: [`Scanarea rețelei pentru viruși`, `Atribuirea unei litere de drive unui folder partajat din rețea (ex: Z:\)`, `Configurarea unei rețele VPN`, `Instalarea unui driver de rețea`],
    correctIndex: 1,
    explanation: `Map network drive = folderul partajat (ex: \\server\share) apare ca un drive (Z:) în This PC. Acces rapid fără a tasta calea de fiecare dată.`,
  },
  {
    id: `devices-139`,
    type: "single",
    topic: `General`,
    prompt: `Dacă o Local Policy și o Group Policy sunt în conflict, care are prioritate?`,
    options: [`Local Policy`, `Group Policy`, `Depinde de utilizator`, `Se anulează reciproc`],
    correctIndex: 1,
    explanation: `Group Policy (de pe server/Active Directory) CÂȘTIGĂ mereu. Ordinea: Local → Site → Domain → OU. Ultima aplicată câștigă.`,
  },
  {
    id: `devices-140`,
    type: "single",
    topic: `General`,
    prompt: `Local Security Policy se aplică doar pe computerul local. True or False?`,
    options: [`True`, `False`],
    correctIndex: 0,
    explanation: `True — Local Policy = doar pe acel PC. Group Policy (din Active Directory) se aplică pe toate PC-urile din domeniu.`,
  },
  {
    id: `devices-141`,
    type: "single",
    topic: `General`,
    prompt: `În Event Viewer, ce indică un eveniment marcat cu un cerc roșu?`,
    options: [`Information — eveniment normal`, `Warning — potențială problemă`, `Error — problemă serioasă`, `Audit success`],
    correctIndex: 2,
    explanation: `Roșu = Error (eroare serioasă, ceva nu a funcționat). Galben = Warning. Albastru = Information (totul e OK).`,
  },
  {
    id: `devices-142`,
    type: "single",
    topic: `General`,
    prompt: `În Event Viewer, un eveniment Warning (triunghi galben) înseamnă că sistemul s-a oprit. True or False?`,
    options: [`True`, `False`],
    correctIndex: 1,
    explanation: `False — Warning = potențială problemă, dar sistemul funcționează. E un avertisment, nu o eroare critică.`,
  },
  {
    id: `devices-143`,
    type: "single",
    topic: `General`,
    prompt: `Unde în Event Viewer găsești informații despre logările reușite/eșuate ale utilizatorilor?`,
    options: [`Application log`, `System log`, `Security log`, `Setup log`],
    correctIndex: 2,
    explanation: `Security log = logări, autentificări, acces la fișiere, modificări de permisiuni. Application = erori de aplicații. System = erori de Windows/drivere.`,
  },
  {
    id: `devices-144`,
    type: "single",
    topic: `General`,
    prompt: `Un driver de placă video cauzează erori la pornirea Windows. În ce log din Event Viewer ar apărea erorile?`,
    options: [`Application`, `Security`, `System`, `Forwarded Events`],
    correctIndex: 2,
    explanation: `System log = erori de drivere, servicii Windows, componente de sistem. Driverele sunt componente de sistem, nu aplicații.`,
  },
];
